### ISSUE TITLE
add_subdirectory given source "nabc" which is not an existing directory.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#100]
hi, the log is here: https://travis-ci.org/Amber-MD/ambertools-ci/jobs/329736526

**Comment by multiplemonomials** [comment]
Oh, that's David Case's new Amber Tool.  I guess it was missing from `mkrelease_at`

**Comment by multiplemonomials** [comment]
Should be fixed now

**Comment by multiplemonomials** [comment]
OK I will push a commit soon that disables nabc from building in release mode

**Comment by multiplemonomials** [comment]
Amber master commit `4e4d5bf` should fix it properly this time.

**Comment by hainm** [comment]
thanks. Just trigger the build. https://travis-ci.org/Amber-MD/ambertools-ci/builds/330214286

**Comment by hainm** [comment]
green again with latest build: https://travis-ci.org/Amber-MD/ambertools-ci/builds/330652931
thanks
