### ISSUE TITLE
why nab + sff breaks on MacOS

### ISSUE THREAD

**Issue by dacase** [Amber-MD/cmake-buildscripts#102]
For me, the cmake build of nab fails on MacOS: the global variable
"nabout" (set in the nab main routnie) is not visible to routines in
libsff.  Any nab test that uses the libsff routines will segfault.  No further need to study
Jamie's tracebacks: if I create a temporary "fix" by "#define nabout stdout" the segfaults
all go away (except for MPI, which is a related issue.)

The historic Makefiles in Amber use static libraries for libsff, and link
nab code with libsff.a.  The CMake version makes dynamic libraries, e.g.
libsff.dylib.  This doesn't seem to work for Mac.

There's lots of ideas in Google-land about this static/dynamic distinction and
its effects on global variables, e.g.:

  stackoverflow.com/questions/39394971/can-i-declare-a-global-variable-in-a-shared-library

Ideas:

1. Alter CMakefiles to do what the historic Makefile do: build a static
library.  Might be as simple as adding the "STATIC" flag to the add_library
command in $AMBERHOME/AmberTools/src/sff/CMakeLists.txt, probably other places
as well.  Or maybe there is some better approach.  (I tried just adding
STATIC, but no luck.  I think variables like "-dylib -undefined dynamic_lookup"
need to get passed when the library is made, and even this may not be enough.)

2.  Get rid of these global variables at the source code level.  This is
clearly possible, but I haven't yet found a simple way to do that.... [Update: I'm working on avoiding use of global variables, but it's a bit tricky.]

3.  Figure out the magic that allows passing global variables like nabout,
mytaskid and numtasks (those are the only three!) to dynamically linked libraries on Mac.

**Comment by multiplemonomials** [comment]
Sorry, I now realize that you emailed me about this back in December, but I somehow missed it.  Whoops!

I tried a fully static build of Amber (`-DSTATIC=TRUE`), and the executables don't segfault.  The only issue is that nab doesn't add `-lgfortran`, which is needed for successful linking with static libraries.  

When I get a chance, I'll try to narrow it down to determine which libraries need to be static for things to work.

**Comment by dacase** [comment]
Hi Jamie:  There are two problems with nab+sff that seem unreleated:

1. The "nabout" file pointer (where output should go) needs to get from the main program to the library routines.  This was originally done as a global variable, and it sounds like you've fixed that.
If not, you can look at the cmake-dac branch, where I wrote set/get routines for nabout that avoid
the need for nabout to be a global variable.  But if your solution works, it sounds fine.

2. There are two other global variables, mytaskid and numtasks, related to MPI.  Here, I think(?)
the problem is that the link step is using gcc rather than mpicc [run mpinab -v on a test file like
$AMBERHOME/AmberTools/test/nab/ltest.nab].  This runs the danger of picking up the wrong mpi libraries.  When I debug, I see that (in parallel) mpiinit() is not returning the correct values for mytaskid and numtasks -- this is not related to passing global info between main and library routines.

Thanks again for all your work on this!

**Comment by multiplemonomials** [comment]
CMake only supports one compiler at a time, so if you just configured with `CC=mpicc`, then it would be impossible to do pan-configuration builds like Amber's system does.  Instead, the CMake `FindMPI` standard library module actually runs the MPI wrappers and extracts the flags and libraries from them, then applies them at link time.  `nab` uses this too, and when you run `mpinab` you should be able to see the MPI flags in the compiler command when you run `nab -v <any nab file>.nab`.

In your case, try setting the CMake variables `MPI_C_COMPILER`, `MPI_CXX_COMPILER`, and `MPI_Fortran_COMPILER` to point to the correct MPI wrappers, then reconfiguring?

Note that you can see what MPI libraries are actually being used with `cmake -DPRINT_PACKAGING_REPORT=TRUE`

**Comment by dacase** [comment]
1.  " the CMake FindMPI standard library module actually runs the MPI wrappers and extracts the flags and libraries from them, then applies them at link time. "

Does cmake use the mpicc/mpif90 in the users PATH to do this?

2. "The only issue is that nab doesn't add -lgfortran, which is needed for successful linking with static libraries."

We may be able to go back to dynamic libraries, although I don't understand why the missing -lgfortran error only affects static libraries.  I think(?) I once got dynamics libsff linking to work on the Mac, but then it broke again.  Static libraries would certainly be simpler--do you think there is a solution to this problem?  [Basically, the current cmake code is trying to use gcc to link libraries
that were compiled using gfortran, and failing.]

**Comment by multiplemonomials** [comment]
> Does cmake use the mpicc/mpif90 in the users PATH to do this?
 
The first time CMake is run, it finds MPI wrappers in the user's path to extract flags from, so yes.

>   Static libraries would certainly be simpler--do you think there is a solution to this problem? 
> [Basically, the current cmake code is trying to use gcc to link libraries that were compiled using gfortran, and failing.]

Do you think that using the Fortran compiler as the link driver would fix the "-lgfortran" issue?

**Comment by multiplemonomials** [comment]
I pushed some new changes last night, and I think that I have fixed nab and mpinab.  I just tested on my Mac VM and `nab` passes all tests.  Can you try it out, @dacase ?

**Comment by dacase** [comment]
Serial nab looks fine on my mac.  I'll get to testing the parallel version soon.  thanks for working on this!

**Comment by multiplemonomials** [comment]
When you get a chance, could you please take a look at #102 ?  I can't troubleshoot that one since I don't know about Sander internals, and it's the last remaining crash that occurs when testing CMake-built Amber.

**Comment by dacase** [comment]
mpinab is working except for the gbnetcdf test ("make gbnetcdf_test").  I'll try to spring some time
free to look at this.

**Comment by dacase** [comment]
Jamie wrote:  "When you get a chance, could you please take a look at #102 ? I can't troubleshoot that one since I don't know about Sander internals, and it's the last remaining crash that occurs when testing CMake-built Amber."

Can you give more details?  "#102" seems to point to this issue, but this is all about nab, not sander.

**Comment by multiplemonomials** [comment]
Sorry, I meant #101

**Comment by dacase** [comment]
I think I can close this issue: I don't see any current problems with nab.
