### ISSUE TITLE
miniconda in path woes

### ISSUE THREAD

**Issue by dacase** [Amber-MD/cmake-buildscripts#106]
The DOWNLOAD_MINICONDA stuff is just driving me nuts!  It's easy to get into a situation where
cmake will exit no matter whether this variable is set to TRUE or FALSE. 

Here's my situation: the Phenix python is first in my PATH, but the $AMBERHOME/miniconda/bin
is later in the path (put there by the $AMBERHOME/amber.sh script.)

If I set DOWNLOAD_MINICONDA=FALSE, cmake complains that scipy is not part of my phenix.python.

If I set DOWNLOAD_MINICONDA=TRUE, cmake says that if found $AMBERHOME/miniconda/bin in the PATH, so says I have to rerun things with DOWNLOAD_MINICONDA=FALSE.

cycle back to the first problem....

Also, there is no configure_cmake option related to this, so I always have to type "e=--extra-cmake-flags -DDOWNLOAD_MINICONDA=xxxx"  (I know, a minor complaint)

Second level of problems:  even without phenix.python getting in the way:

the $AMBERHOME/amber.sh scripts puts $AMBERHOME/miniconda/bin in the PATH (why??).  But
this then can conflict with the cached behavior of DOWNLOAD_MINICONDA.  So then, if you make a change to any local CMakeLists.txt file, and try to do a local make, the system goes back to the original cmake configure step, noticies that miniconda is in the path, and complains.

I'm not sure what the best way to handle this is, but there must be something that would be an improvement.

Sorry for the long rant....I got into this issue just trying to figure out what is going on with the pmemd.cuda build.

**Comment by dacase** [comment]
OK: maybe its more complex than what I had before.  I put $AMBERHOME/miniconda/bin first in my path.  Then if I invoke cmake with DOWNLOAD_MINICONDA=FALSE, I get this:

-- Found system Anaconda at /home/case/amber_ci/miniconda.  It will be used as a
 Python interpereter, and for additional shared libraries.
-- It is not possible to avoid using Anaconda if it is on the PATH.  To build Amber without using Anaconda, remove it from your PATH.
-- To use a different Anaconda install, just move it to the front of your PATH and rerun CMake.
-- To change the Python interpreter in use to a different one inside Anaconda, set the PYTHON_EXECUTABLE variable to point to it.
-- Python version 2.7 -- OK
Checking for Python package scipy -- not found
CMake Error at cmake/PythonBuildConfig.cmake:54 (message):
  Missing required Python packages: scipy. 

So cmake found my miniconda python, but thinks it doesn't have scipy.  But If I try this:

casegroup5% /home/case/amber_ci/miniconda/bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import scipy
>>> quit()

I don't have any trouble inporting scipy.

Do you see what is going on?

**Comment by dacase** [comment]
Yet more (modestly related, but I think real users will be seeing the same problems I'm having):

I completely removed my build and install directories, working from a clean git master version of the code.  I ran configure_cmake with the --skip-python flag:

CMake command: /usr/bin/cmake  -DCMAKE_INSTALL_PREFIX=/home/case/amber_ci -DCUDA=TRUE -DBUILD_GUI=FALSE -DBUILD_PYTHON=FALSE -DGTI=TRUE -DCOMPILER=GNU -DINSTALL_TESTS=TRUE "-DDISABLE_TOOLS=" /home/case/amber_git

But I still get the python-related messages I was trying to avoid:

CMake Error at cmake/PythonInterpreterConfig.cmake:46 (message):
  We highly recommend letting AMBER install a Python environment with all
  prerequisites.....

Should this python check not be skipped if BUILD_PYTHON is set to false?

**Comment by multiplemonomials** [comment]
That is very strange, and is not behavior that I've seen on any of my systems.  

What happens if you run `cmake/python_packagecheck.py scipy` with miniconda and with phenix python?  That's all the the CMake check is doing.

**Comment by hainm** [comment]
> Here's my situation: the Phenix python is first in my PATH, but the $AMBERHOME/miniconda/bin
is later in the path (put there by the $AMBERHOME/amber.sh script.)

what is the output for `which python` in this case? I thought phenix hide that "python" and let user use "phenix.python".

**Comment by dacase** [comment]
Here's the result about python and scipy:

casegroup5% which python
/home/casegroup/phenix/build/bin/python
casegroup5% /home/casegroup/phenix/build/bin/python cmake/python_packagecheck.py scipy
casegroup5% echo $?
1
casegroup5% /home/case/amber_ci/miniconda/bin/python cmake/python_packagecheck.py scipy
casegroup5% echo $?
0

So:  phenix puts a "python" (not just phenix.python) in the $PATH.

The Phenix python is missing scipy (as expected: they have a policy not to allow this.
The amber miniconda python does seem to have scipy, as it should.

But in the second comment above, cmake appears to be examining the python installation
in /home/case/amber_ci/miniconda, and claiming it is missing scipy....

**Comment by dacase** [comment]
At a higher level:

If cmake finds a miniconda installation in the installation directory, why not just use that?  Or, if it finds miniconda in the build directory, can in not use that?

Assuming that cmake itself cannot be interactive in way we are used to (asking the user for permission to download), why don't we push the miniconda download stuff into configure2_cmake, getting python stuff setup there (in the way we do now), and then invoke cmake with DOWNLOAD_MINICONDA=FALSE?  That way, cmake could assume the existence of a correct python
installation.

**Comment by multiplemonomials** [comment]
The reason that CMake handles Miniconda installation is the installer and package generation.  The idea is for the generated packages to bundle Miniconda with them, so they can have a built-in Python out of the box.  After building using Miniconda, CMake will copy Miniconda to the installation directory and then include it in the package.  If the script were used to install Miniconda, this wouldn't work any more.

Then again, the wrapper script doesn't currently have packaging-related options anyway, so I'm not sure if this would actually cause any issues.

**Comment by multiplemonomials** [comment]
I figured it out!  The issue was that even though CMake reports that it is using Anaconda, it still ends up using the first python executable on the path.  So, it was still invoking phenix's python, and that's why the scipy test was failing.  I just pushed a fix, you should be able to pull the latest changes and have no more scipy errors.  

Also, you can disable the scipy check entirely with the CMake flag `-DSKIP_PYTHON_PACKAGE_CHECKS=TRUE`

**Comment by dacase** [comment]
Thanks for the explanation.  But I'd still hope that CMake could handle miniconda better.  It's OK
on a clean installation where miniconda is being downloadeds  (although the user still has to run cmake twice); things get murkier if miniconda has been downloaded before.

While I'm thinking about it: the legacy installation creates an AMBERHOME/bin/amber.python link, that points to ../minconda/bin/python; plus other similar links.  This should be done with CMake: there
are scripts that assume the existence of an amber.pytyon

**Comment by multiplemonomials** [comment]
On a side note, what would you think about putting an "automatic bug report" option in the configure script?  Like this: http://ambermd.org/pmwiki/pmwiki.php/Main/CMake-Reporting-A-Bug

**Comment by multiplemonomials** [comment]
Also, I just realized that there was supposed to be a `configure_cmake` option to handle miniconda, but it hasn't been working because I wrote an if statement wrong.  I'll commit a fix, and you won't have to use `--extra-cmake-flags` for that any more.

**Comment by multiplemonomials** [comment]
Have you had a chance to check if this issue is still bothering you?  I think I fixed it in `configure_cmake`.

**Comment by multiplemonomials** [comment]
@dacase Can you confirm if this issue has been fixed, or is it still a problem?

**Comment by multiplemonomials** [comment]
Also, as of f4a8922475707064e6d116118860dcc77ed0cae0 the cmake build system now creates symlinks for Python programs instead of just adding the miniconda bin dir to the path, exactly as you described.

**Comment by multiplemonomials** [comment]
OK I'm closing this since I'm fairly confident it's fixed.
