### ISSUE TITLE
make[2]: *** No rule to make target `AmberTools/src/pbsa/CMakeFiles/libpbsa.dir/build'.  Stop.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#107]
hi,

I think this error is caused by today's merge from Ray Luo's branch ( pbsa-dev).

Log is here: https://travis-ci.org/Amber-MD/ambertools-ci/jobs/349015592

**Comment by dacase** [comment]
I've tried to figure out how to update the CMakeLists.txt file to account for all of Ray's new changes, but I think this goes beyond my CMake capabilities.  I don't see the exact error message above,
but I still can't get libpbsa to build under CMake.

I think(?!?) the main reason might be this: the legacy make is building a static library, which can have unsatisfied external dependencies.  But CMake wants to build a dynamic library, which doesn't allow for that.  But I'm way overtaxed right now with other stuff, so won't have much time to work on this.

Perhaps we could just have CMake skip libpbsa temporarily?

**Comment by hainm** [comment]
> I don't see the exact error message above

The nightly build is using cmake command directly (below). I guess this would make the difference?
```
    cmake -DCOMPILER=GNU \
        -DFORCE_INTERNAL_LIBS=readline \
        -DCMAKE_INSTALL_PREFIX=$HOME/TMP/install \
        -DBUILD_GUI=FALSE \
        -DUSE_MINICONDA=FALSE \
        $HOME/amber$version
```

**Comment by multiplemonomials** [comment]
It should be fixed now. It's midterms week here for me so I'm kinda swamped as well.

**Comment by hainm** [comment]
thanks Jamie.
