### ISSUE TITLE
add_subdirectory given source "examples" which is not an existing directory.

### ISSUE THREAD

**Issue by tluchko** [Amber-MD/cmake-buildscripts#109]
I'm trying to build Amber18 RC2 with cmake but the configure fails with the error:

```
CMake Error at CMakeLists.txt:172 (add_subdirectory):
  add_subdirectory given source "examples" which is not an existing
  directory.
```

I'm on CentOS 6.6 using GNU 4.4.7. I'm attaching the CMakeError.log, CMakeCache.txt, and the cmakeoutput.log.
[CMakeCache.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1834314/CMakeCache.txt)
[cmakeoutput.log](https://github.com/Amber-MD/cmake-buildscripts/files/1834315/cmakeoutput.log)
[CMakeError.log](https://github.com/Amber-MD/cmake-buildscripts/files/1834316/CMakeError.log)

**Comment by multiplemonomials** [comment]
Oh, whoops, I think I assumed that that directory would be in `mkrelease_at`, but it actually isn't.  David already fixed this in master branch.  For the release candidate, you can just delete line 172 of `CMakeLists.txt` to fix it.

**Comment by tluchko** [comment]
This is fixed in RC3.
