### ISSUE TITLE
CMake equivalent of FLIBS?

### ISSUE THREAD

**Issue by dacase** [Amber-MD/cmake-buildscripts#121]
I'm trying to convert various NAB codes to C.  In the legacy build system, config.h has an FLIBS variable which tells the nab compiler which things to link in.  FLIBS itself depends on things like
what linear algebra packages and fft libraries have been specified.

I'm unclear about how to translate this idea to cmake, and don't seem to see any direct analogue in the existing CMakeLists files.

The example is in the rism-cleanup branch, in the AmberTools/src/rism directory.  You can see how rism3d.snglpnt is build in the legacy Makefile (using FLIBS from config.h).  What should I put into the CMakeLists.txt file to build inside cmake?

...thx...dac

**Comment by multiplemonomials** [comment]
I made a target called `netlib`, defined in `NetlibConfig.cmake`, which resolves to the current floating-point libraries in use, either MKL + ARPACK, or BLAS+LAPACK+ARPACK.

**Comment by dacase** [comment]
OK...thanks...I got things to work.  So I'm going to close this issue.
