### ISSUE TITLE
dependency failure for CartHess.py

### ISSUE THREAD

**Issue by dacase** [Amber-MD/cmake-buildscripts#124]
make install on MacOSX fails for me very near the end of the install process:

Considering /home/case/amber_ci//bin/CartHess2FC.py
CMake Error at /opt/local/share/cmake-3.11/Modules/GetPrerequisites.cmake:836 (message):
  /opt/local/bin/otool failed: 1

  /opt/local/libexec/llvm-4.0/bin/llvm-objdump:
  '/home/case/amber_ci//bin/CartHess2FC.py': The file was not recognized as a
  valid object file

  fatal error: /opt/local/bin/otool: internal objdump command failed

Call Stack (most recent call first):
  /home/case/amber_gitlab/cmake/BundleOSXDependencies/BundleOSXDependencies.cmake:127 (get_prerequisites)

I poked around a bit, but didn't find anything obvious.  A python script is probably not a valid object file, but I didn't see where to go next, and hoped that Jamie or Hai would recognize the symptom.

(Pretty standard cmake invocation, downloading miniconda into the build directory)

...thx...dac

**Comment by multiplemonomials** [comment]
Huh, as far as I can tell, whatever version of CMake/Xcode/OSX you have considers analyzing dependencies of a script to be an error, while mine was just silently failing.  Well, all Python scripts should be excluded now.
