### ISSUE TITLE
install failure for mmpbsa.py.MPI on OSX

### ISSUE THREAD

**Issue by dacase** [Amber-MD/cmake-buildscripts#125]
I'm still getting this install failure on MacOS, with the gitlab master branch, following a
"git subtree pull --squash --prefix=cmake git@github.com:amber-md/cmake-buildscripts"

-- Considering /home/case/amber_ci//bin/MMPBSA.py.MPI
CMake Error at /opt/local/share/cmake-3.11/Modules/GetPrerequisites.cmake:836 (message):
  /opt/local/bin/otool failed: 1

  /opt/local/libexec/llvm-4.0/bin/llvm-objdump:
  '/home/case/amber_ci//bin/MMPBSA.py.MPI': The file was not recognized as a
  valid object file

  fatal error: /opt/local/bin/otool: internal objdump command failed

Call Stack (most recent call first):
  /home/case/amber_git/cmake/BundleOSXDependencies/BundleOSXDependencies.cmake:138 (get_prerequisites)

It looks like commit 71d4165156c521790b5e41ef2dbf43f5f2a3cd4f, 
"Remove python scripts from list of things in bin to be analyzed for c…" seems relevant.  Could it be that it doesn't recognize MMPBSA.py.MPI because that file doesn't end in ".py"?  (wild-ass guess).

Aside: not sure why this works on jenkins: (1) maybe jenkins is not building with cmake on a Mac;
(2) maybe jenkins is building but not installing;  (3) ...??

**Comment by multiplemonomials** [comment]
Yep, looks like you guessed it!  I'll update that list when I get a chance.  

On a side note, I don't believe that Jenkins has any mac builds at all currently.  For some reason the version of otool on my Mac VM doesn't appear to complain when passed an invalid file, so apperently the first place these errors showed up was on your machine.

**Comment by swails** [comment]
Jenkins doesn’t have any Mac builds yet, but I added a Mac Mini slave finally. 

I got a SSD to put in it, but haven’t gotten around to installing yet (prime day deal). But it should still “work” once I add a stage in the parallel stage block for it.

**Comment by multiplemonomials** [comment]
I tried updating the list in 52dc02808, but apparently was defeated by some scripts not having file extensions.  I'll just have it scan the contents of bin using `file` and skip anythin that isn't a `Mach-O Executable`.

**Comment by multiplemonomials** [comment]
Fixed in Amber master, you shouldn't see this any more.
