### ISSUE TITLE
Mac OS X build failures on Jenkins

### ISSUE THREAD

**Issue by swails** [Amber-MD/cmake-buildscripts#126]
I've finally gotten around to [creating a build recipe for OS X on Jenkins](https://gitlab.ambermd.org/amber/amber/merge_requests/27), and my intention is to use CMake.  However, I'm getting an error related to what looks like [missing dependencies](https://jenkins.jasonswails.com/blue/organizations/jenkins/AmberGitLab%2FAmberMergeGatePipeline/detail/AmberMergeGatePipeline/138/pipeline/20#step-52-log-1521).

The relevant error line is this:

```
[ 58%] Building Fortran object AmberTools/src/sander/CMakeFiles/sander_base_obj.dir/mdwrit.F90.o
/Users/swails/Jenkins/workspace/AmberGitLab/AmberMergeGatePipeline/AmberTools/src/sander/mdwrit.F90:12:7:

    use nfe_sander_hooks, only : nfe_on_mdwrit => on_mdwrit
       1
Fatal Error: Can't open module file 'nfe_sander_hooks.mod' for reading at (1): No such file or directory
compilation terminated.
```

Indeed, if you look at the build log, `nfe-sander-hooks.F90` was never built, so `nfe_sander_hooks.mod` was never generated, and compiling `mdwrit.F90` fails as a result.

The legacy build system captured this dependency in `depends`:

```
mdwrit.o: \                                                                                                                                 
                    copyright.h\
                    ../include/dprec.fh\
                    nfe-config.h\
                    file_io_dat.o\
                    nfe-sander-hooks.o\
                    nfe-sander-proxy.o\
                    binrestart.o\
                    remd.o\
                    sglds.o\
                    nonbond_list.o
```

I suspect that ending parallel builds (`make -j1`) would fix the problem.  However, I'd like to avoid that if possible.

Any ideas how to fix this?

**Comment by swails** [comment]
Also, I had to add the following to my environment to work around #116:

```
PERL_USE_UNSAFE_INC = 1
```

Is there a better workaround?

**Comment by multiplemonomials** [comment]
Hmm that perl error should have already been fixed, since I set `PERL5LIBS` to the current directory when building.  Even so, I added the `PERL_USE_UNSAFE_INC=1` environment variable as well.

**Comment by multiplemonomials** [comment]
Ah, got it!  mdwrit.F90 was using some preprocessor syntax that CMake was choking on.  I changed it and now the dependency is detected.

**Comment by multiplemonomials** [comment]
And it turns out that I screwed up my fix to #116 so that it only applied on Windows!  Should be fixed now.

**Comment by multiplemonomials** [comment]
Also, @swails I figured out why the Sander LES API tests are failing on Jenkins for the CMake GNU build.  It's because `libsander` is getting built as static, and the test tries to link it like a dynamic library.  The fix would be to either make sure the tests links all of sander's dependency libraries (`libamber_common, `libsqm`, etc.), or just have it bail out of there is no `libsanderles.so` like the non-LES API test does.

**Comment by swails** [comment]
libsander.so is critical to the proper functioning of the Python API.  What needs to be done to get those building correctly?

**Comment by multiplemonomials** [comment]
Alright, OS X build is working now!
