### ISSUE TITLE
CMake equivalent to AMBERBUILDFLAGS

### ISSUE THREAD

**Issue by tluchko** [Amber-MD/cmake-buildscripts#128]
Is there something equivalent or similar to AMBERBUILDFLAGS?  With the original build system I could do something like

```make AMBERBUILDFLAGS='...' install```

to add some extra compiler flags after I had already configured everything.  

The use case is that I'd like to turn on some non-standard compiler debug options without having to edit the CMake files, reconfigure and recompile.

**Comment by multiplemonomials** [comment]
Yep!  Just use `-DCMAKE_C_FLAGS=...` to add extra C flags.  There are also `CMAKE_CXX_FLAGS` and `CMAKE_Fortran_FLAGS` for C++ and Fortran compiler flags.

**Comment by tluchko** [comment]
Thanks. This should work but it does require re-running `cmake` before running `make`.  Not a huge inconvenience though.

 I'll add that you can also edit the files in the `$AMBERHOME/cmake` directory and, the next time you `make`, `cmake` will automatically be run to capture any updates.  In this case, I am modifying the `CMAKE_Fortran_FLAGS_DEBUG` variable in `$AMBERHOME/cmake/CompilerFlags.cmake`. Care needs be taken to not accidentally commit the changes.
