### ISSUE TITLE
Fix OS X package

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#15]
I have worked for many hours on the OS X packaging, but I am stuck on two issues.  First, the icon always shows as the default Apple one.  Second, nothing happens when you double-click the package (it's supposed to run `amber-interactive.sh`, which gives you a console).

@hainm Can you use your mac experience to help me with this?

**Comment by hainm** [comment]
Sorry I have zero experience for those. :(

Hai

**Comment by hainm** [comment]
by the way, we currently support binary distribution

```
Binary distribution: Users of the conda python system can install a serial, binary (pre-compiled) distribution as follows:
  conda install ambertools=17 -c http://ambermd.org/downloads/ambertools/conda/
This should work for Linux and MacOS systems, with python versions 2.7 to 3.6; but it is experimental, and does not provide access to parallel or gpu-optimized codes. This provides a simple way to get started with AmberTools, and to install it into many workflows, but it is not a substitute for the full source-code distributions listed above. 

Non-conda users can follow: 
  wget http://ambermd.org/downloads/install_ambertools.sh 
  # Or: curl http://ambermd.org/downloads/install_ambertools.sh -O 
  bash install_ambertools.sh -v 3 --prefix $HOME --non-conda 
```

**Comment by hainm** [comment]
@multiplemonomials How can I make a package?

Here does not tell anything: http://ambermd.org/pmwiki/pmwiki.php/Main/CMake-Creating-Packages

**Comment by multiplemonomials** [comment]
Sorry, I have not gotten around to writing that yet.  I will fill it in right now.

**Comment by multiplemonomials** [comment]
Package works properly (except for the libgfortran bundling) as of merge of experimental to master.  Also the documentation is essentially complete.
