### ISSUE TITLE
make -j 2

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#20]
Jamie,

does cmake support that yet? I am getting error for cpptraj (which worked fine for `make -j 1`)

[make_j2.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1206742/make_j2.txt)

**Comment by multiplemonomials** [comment]
This is the same error as #21.  It's just hard to see because it's in the middle of the build log.  CMake absolutely supports parallel build, but it can be a little hard to find build errors when they occur.

**Comment by hainm** [comment]
what's about "make test" (kind of tricky question :D )
