### ISSUE TITLE
nab error

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#21]
FYI

```
/Users/haichit/amber_git/build/AmberTools/src/nab/CMakeFiles/CmakeVectorData-nab-Release.cpp:4:10: fatal error: 'initializer_list' file not found
#include <initializer_list>
         ^
1 error generated.
make[2]: *** [AmberTools/src/nab/CMakeFiles/nab.dir/CMakeFiles/CmakeVectorData-nab-Release.cpp.o] Error 1
make[1]: *** [AmberTools/src/nab/CMakeFiles/nab.dir/all] Error 2
make: *** [all] Error 2
```

[make_j1.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1206744/make_j1.txt)

[cmake_log.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1206745/cmake_log.txt)

**Comment by multiplemonomials** [comment]
Could I have `CMakeCache.txt` for this one please?

**Comment by hainm** [comment]
Uhm, in your wiki you don't mention that :D. I will retry.

```
If the error happens when running make
the full output of running make VERBOSE=1 in your build directory
```

**Comment by hainm** [comment]
[CMakeCache.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1206758/CMakeCache.txt)

**Comment by multiplemonomials** [comment]
This one is just a special case where I do need `CMakeCache.txt`.  It turns out that this is sort of a CMake issue.  CMake is telling me that your compiler supports C++11 initializer lists, but it actually doesn't.  I'll just take out the code that uses them since it isn't doing much anyway.
