### ISSUE TITLE
No *.so files for pytraj

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#22]
Hi,

```bash
$ python -c "import pytraj; print(pytraj)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/haichit/amber_git/build_gnu/lib/python3.5/site-packages/pytraj/__init__.py", line 24, in <module>
    from .utils.misc import info
  File "/Users/haichit/amber_git/build_gnu/lib/python3.5/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "/Users/haichit/amber_git/build_gnu/lib/python3.5/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: No module named 'pytraj.core.topology_objects'
```

[CMakeCache.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1206796/CMakeCache.txt)

```
export PATH=/usr/local/gfortran/bin/:$PATH
cmake -DFORCE_DISABLE_TOOLS=mtkpp -DCMAKE_INSTALL_PREFIX=`pwd` -DCOMPILER=gnu ../amber
make -j 1
make install
source amber.sh
```

**Comment by multiplemonomials** [comment]
This problem seems to be something with the Python build system.  CMake runs the command
```
env --unset=AMBERHOME 
		CPPTRAJ_HEADERDIR=${CMAKE_CURRENT_SOURCE_DIR}/../cpptraj/src CPPTRAJ_LIBDIR=$<TARGET_FILE_DIR:libcpptraj>
		CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER}
		python setup.py build_ext --no-setuptools -b ${BUILD_DIR} --disable-openmp
```
to build pytraj, and 
```
env  --unset=AMBERHOME 
CPPTRAJ_HEADERDIR=${CMAKE_CURRENT_SOURCE_DIR}/../cpptraj/src
CPPTRAJ_LIBDIR=${CPPTRAJ_LIBDIR}
CXX=${CMAKE_CXX_COMPILER} CC=${CMAKE_C_COMPILER}
	python
  	./setup.py build_ext --no-setuptools -b ${BUILD_DIR} --disable-openmp install --prefix=${CMAKE_INSTALL_PREFIX}
```
to install it.  For some reason, this causes the .so/.pyd files to not get copied.  Any idea why this is happening?

**Comment by hainm** [comment]
Not sure. Can we replace "build_ext" by "build"?
(and pytraj is using seuptools in amber now: 23225639c65dc10a7cd49a31b7f3f0f9bef35970)

Normally
```python
python setup.py build # will create ./build folder
```

**Comment by hainm** [comment]
> 	python
  	./setup.py build_ext --no-setuptools -b ${BUILD_DIR} --disable-openmp install --prefix=${CMAKE_INSTALL_PREFIX}
to install it. 

You are still using "build_ext" here.

**Comment by hainm** [comment]
oh mistake here: https://github.com/Amber-MD/pytraj/blob/master/CMakeLists.txt#L60

should be "setup.py install).

**Comment by hainm** [comment]
I fixed here: https://github.com/Amber-MD/pytraj/pulls

But still need to add `build/lib/pythonX.Y/site-packages/` to PYTHONPATH.

**Comment by multiplemonomials** [comment]
My goal with all of those strange arguments is to get the built extension modules to go into the build directory tree and not the source directory.  If, when installing, I just did `setup.py install`, then it wouldn't know where to get the built files.  I have to do `setup.py build -b <path to build dir> install`.  You probably know this but I'm not sure.

I'll try changing `build_ext` to `build`, and setting PYTHONPATH during install.  If I can't get `build -b` to work, then I'll just let it build in the source directory.

**Comment by hainm** [comment]
>setting PYTHONPATH during install. 

ah, please do this for ParmEd too (check Makefile for others).
