### ISSUE TITLE
wrong library path for pytraj?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#25]
Please see

cmake (show `-L/Users/haichit/amber_git/build/AmberTools/src/cpptraj/src `)

`
/usr/bin/clang++ -bundle -undefined dynamic_lookup -L/Users/haichit/miniconda3/lib -arch x86_64
 build/temp.macosx-10.6-x86_64-3.5/pytraj/analysis/c_action/actionlist.o 
-L/Users/haichit/amber_git/build/AmberTools/src/cpptraj/src -L/Users/haichit/miniconda3/lib 
-lcpptraj -o build/lib.macosx-10.6-x86_64-3.5/pytraj/analysis/c_action/actionlist.cpython-35m-
darwin.so -O0 -ggdb
`

non-cmake (correct: `-L/Users/haichit/amber_git/amber/lib`)

`
clang++ -bundle -undefined dynamic_lookup -L/Users/haichit/miniconda3/lib -arch x86_64 build/temp.macosx-10.6-x86_64-3.5/pytraj/analysis/c_action/actionlist.o -L/Users/haichit/amber_git/amber/lib -L/Users/haichit/miniconda3/lib -lcpptraj -o build/lib.macosx-10.6-x86_64-3.5/pytraj/analysis/c_action/actionlist.cpython-35m-darwin.so -O0 -ggdb
`

**Comment by multiplemonomials** [comment]
what's the problem here?

**Comment by hainm** [comment]
uhm I think I am messing up between different builds. Close for now.

**Comment by hainm** [comment]
damn, turns out that Apple guys enable `DYLD_LIBRARY_PATH` again.

(they disabled a while ago: https://github.com/oracle/node-oracledb/issues/231)

**Comment by multiplemonomials** [comment]
wow, that… seems like a fiasco

**Comment by agoetz** [comment]
What is the problem with DYLD_LIBRARY_PATH? I wasn't aware that we rely on it, and I guess we shouldn't?

**Comment by hainm** [comment]
Originally setting DYLD_LIBRARY_PATH is just like setting LD_LIBRARY_PATH in Linux. 
Without "source amber.sh" (in cmake install), pytraj can not find `@rpath/libcpptraj.dylib`.

In non-cmake, pytraj uses absolute path (e.g: /Users/haichit/amber_git/amber/lib/libcpptraj.dylib)

> I wasn't aware that we rely on it, and I guess we shouldn't?

yeah,  I agree. I should use absolute path in this case. But not sure if that's easy for cmake here because the install location will be changed? 

When I do binary build (AT17), `@rpath/...` will be used but `@loader_path` will be set to corresponding location.
