### ISSUE TITLE
make test?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#28]
Jamie,

Is "make test" supported yet? I've tried and got no output.

**Comment by multiplemonomials** [comment]
Up until now, I've been running `AmberTools/test/test_at_serial.sh`

**Comment by hainm** [comment]
> AmberTools/test/test_at_serial.sh

From source code, right?

**Comment by multiplemonomials** [comment]
yeah

**Comment by multiplemonomials** [comment]
Can I close this issue or are you still having trouble?
