### ISSUE TITLE
simplify build on Windows?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#29]
If you really want to use MinGW, I would suggest to use msys2 with `pacman` package manger.
http://www.msys2.org/

E.g: below
http://ambermd.org/pmwiki/pmwiki.php/Main/CMake-On-Windows
> Download win-flex-bison flex from https://sourceforge.net/projects/winflexbison/files/, extract it to your Program Files directory, and put it on your PATH.

> Install Python, and put it on your PATH

They are could be replaced by `pacman ...`

I am not enjoying to test stuff on Windows so it's up to you. :d

**Comment by hainm** [comment]
pacman: https://github.com/Amber-MD/pytraj/blob/master/appveyor.yml#L8

**Comment by multiplemonomials** [comment]
This `msys2` seems fine, but if you built stuff using it, then you would be dependent on the `msys2` DLLs, and you'd be using POSIX emulation.  It would probably work for `flex`, but `msys2` python is probably not interoperable with native Windows python, or with Windows Miniconda.  I want Amber to be able to work without any of these crutches. I know that the Windows setup process is kind of a pain, but when you follow it, you get the ability to build self-contained Win32 executables that use no emulation and only depend on a few small MinGW libraries.

**Comment by hainm** [comment]
ok. If you can make Amber works with Miniconda on Windows (pytraj in this case), you're the man.

**Comment by multiplemonomials** [comment]
I actually got very close to getting this to work a week ago.  I was just getting some strange link error that I couldn't figure out.  I'll post it when I get a chance.

**Comment by multiplemonomials** [comment]
It gets about half way through building the Cython extensions, then dies with:
```
   Creating library build\temp.win-amd64-2.7\Release\pytraj\core\coordinfo.lib and object build\temp.win-amd64-2.7\Release\pytraj\core\coordinfo.exp
skipping 'pytraj\core\c_core.cpp' Cython extension (up-to-date)
building 'pytraj\core\c_core' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src -IC:\Users\Jamie\Documents\amber-submodules\pytraj\pytraj -IC:\Python27\include -IC:\Python27\PC /Tppytraj\core\c_core.cpp /Fobuild\temp.win-amd64-2.7\Release\pytraj\core\c_core.obj
c_core.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\Topology.h(67): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\Topology.h(78): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\Topology.h(88): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixDbl.h(23): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixDbl.h(27): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixDbl.h(36): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixDbl.h(38): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixFlt.h(20): warning C4244: 'argument': conversion from 'double' to 'const float', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixFlt.h(20): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixFlt.h(24): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_MatrixFlt.h(32): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
c:\users\jamie\documents\amber-submodules\cpptraj\install\src\TrajinList.h(36): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data
pytraj\core\c_core.cpp(4833): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\Grid.h(39): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\Grid.h(38): note: while compiling class template member function 'void Grid<double>::ReverseIndex(long,int &,int &,int &) const'
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_GridDbl.h(31): note: see reference to function template instantiation 'void Grid<double>::ReverseIndex(long,int &,int &,int &) const' being compiled
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\DataSet_GridDbl.h(36): note: see reference to class template instantiation 'Grid<double>' being compiled
C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\src\Grid.h(40): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\exception(358): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\Jamie\Documents\amber-submodules\cpptraj\install\lib /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild\amd64 cpptraj.lib build\temp.win-amd64-2.7\Release\pytraj\core\c_core.obj /OUT:build\lib.win-amd64-2.7\pytraj\core\c_core.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\pytraj\core\c_core.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\pytraj\core\c_core.pyd.manifest
   Creating library build\temp.win-amd64-2.7\Release\pytraj\core\c_core.lib and object build\temp.win-amd64-2.7\Release\pytraj\core\c_core.exp
c_core.obj : error LNK2019: unresolved external symbol "protected: static char MaskTokenArray::SelectedChar_" (?SelectedChar_@MaskTokenArray@@1DA) referenced in function "int __cdecl __pyx_pf_6pytraj_4core_6c_core_8AtomMask___cinit__(struct __pyx_obj_6pytraj_4core_6c_core_AtomMask *,struct _object *)" (?__pyx_pf_6pytraj_4core_6c_core_8AtomMask___cinit__@@YAHPEAU__pyx_obj_6pytraj_4core_6c_core_AtomMask@@PEAU_object@@@Z)
build\lib.win-amd64-2.7\pytraj\core\c_core.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\link.exe' failed with exit status 1120
```

**Comment by multiplemonomials** [comment]
I checked, and I'm pretty sure that that symbol is defined in `cpptraj.lib`.   I can't find where it's being called either.  Any ideas?

**Comment by hainm** [comment]
same compiler for cpptraj.lib?

**Comment by multiplemonomials** [comment]
Yeah, I did use the same compiler

**Comment by hainm** [comment]
uhm, I am not expect here and below is just from google search

Make sure to use correct MVS version. Which mean we should use identical compiler version for both Python and pytraj.
https://conda.io/docs/build_tutorials/windows.html#microsoft-visual-studio

**Comment by hainm** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by multiplemonomials** [comment]
Hahaha!  I got it working on Windows!

```
>>> pytraj.run_tests()
try to load sample data
try to make all action objects
try to make all analysis objects
try to make all dataset stuff
try to make structure-related objects
try to create Trajectory-like objects
other stuff. throw all tests don't belong anywhere else here
OK
```

**Comment by multiplemonomials** [comment]
[Here](https://github.com/Amber-MD/cmake-buildscripts/files/1219569/pytraj-2.0.2.dev0-py3.6-win-amd64.egg.zip) is the egg file (wrapped in a .zip because GitHub won't accept .egg files).  It requires 
[these DLLs](https://github.com/Amber-MD/cmake-buildscripts/files/1219572/cpptraj-and-netcdf-dlls-8_12_2017.zip) to be in your PATH for it to work, plus the VS2015 runtime (which is included with Python so it shouldn't be a problem).

**Comment by multiplemonomials** [comment]
I used standard CPython 3.6 at the moment.  I was not able to get a Python 2.7 build because it needs a Microsoft compiler so old that the install discs have been found petrified in amber.

**Comment by hainm** [comment]
> Hahaha! I got it working on Windows! Yesss!!

fantastic.

**Comment by multiplemonomials** [comment]
OK, here is issue 1: On Windows, libraries do not usually have a "lib" prefix.  The CMake build system generates `libcpptraj.lib`, with the prefix, and pytraj's build system looks for `libcpptraj.lib`.  So far, so good.  However, whatever you pass to Distutils makes Python try to link to `cpptraj.lib` instead of `libcpptraj.lib`.  So, you have to copy `libcpptraj.lib` to `cpptraj.lib` to make the build work.  On Windows, pytraj needs to add the "lib" prefix when it passes the DLL name to Python to make this work.

**Comment by hainm** [comment]
> The CMake build system generates libcpptraj.lib

so can we make it "cpptraj.lib"?

**Comment by multiplemonomials** [comment]
Ah, actually no.  That's almost impossible to do in CMake because the target is actually called `libcpptraj` (to differentiate it from the `cpptraj` executable).

**Comment by hainm** [comment]
so just add extra command to rename it?

**Comment by multiplemonomials** [comment]
It's possible but it would be kind of ugly.  Can't you just change cpptraj to pass a different DLL name to distutils on Windows?

**Comment by multiplemonomials** [comment]
## Issue 2: exports from CPPTRAJ
As you probably know, MSVC requires that you explicitly export symbols in a DLL (just like `gcc` with `-fvisibility=hidden`).  Normally, this would require me to put a `__declspec(dllexport)` on EVERY class in cpptraj that Pytraj uses (blargh).  The most recent version of CMake contains a hack (`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`) which will read through the symbols and then export all of them, just like MinGW does.  However, this doesn't work with global variables specifically.  So, any __cpptraj global variables used by pytraj__ need a `__declspec(dllexport)` declaration to work properly.  This is what was causing the link error I posted earlier.

I hacked together a build by just typing the declarations in, but they need to be done properly with preprocessor macros.  So, we need to talk with @drroe and get those declarations added to the `cpptraj` source.  I have found that they are only needed in 6 places:
```
MaskTokenArray::SelectedChar_
MaskTokenArray::UnselectedChar_
Atom::AtomicElementNum
Atom::AtomicElementName
Atom::AtomicElementMass
Atom::AtomicElementRadius
```

**Comment by multiplemonomials** [comment]
## Issue 3: pytraj DLL handling
Pytraj is installing `libcpptraj.lib`, but the library it actually needs to install is `libcpptraj.dll`.  To find it, you could use `$CPPTRAJ_LIBDIR/../bin/libcpptraj.dll`, or you could just have the user pass it as a another argument (`CPPTRAJ_DLLDIR`?).

**Comment by multiplemonomials** [comment]
## Issue 4: build_wheel.py
After building and making a package with `setup.py bdist`, I tried to use your `build_wheel.py` script to create a wheel like you wanted, but it errored out and I have no idea why.
```
J:\amber-cmake\amber\AmberTools\src\pytraj>python scripts\build_wheel.py dist\pytraj-2.0.2.dev0.win-amd64.tar.gz
Using conda to create env
creating pytraj3.6 envconda create -n pytraj3.6 python=3.6 numpy --yes
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment J:\amber-cmake\amber-install\miniconda\envs\pytraj3.6:

The following NEW packages will be INSTALLED:

    mkl:            2017.0.3-0
    numpy:          1.13.1-py36_0
    pip:            9.0.1-py36_1
    python:         3.6.2-0
    setuptools:     27.2.0-py36_1
    vs2015_runtime: 14.0.25420-0
    wheel:          0.29.0-py36_0

mkl-2017.0.3-0 100% |###############################| Time: 0:00:49   2.70 MB/s
vs2015_runtime 100% |###############################| Time: 0:00:00   2.55 MB/s
python-3.6.2-0 100% |###############################| Time: 0:00:12   2.69 MB/s
numpy-1.13.1-p 100% |###############################| Time: 0:00:01   2.62 MB/s
setuptools-27. 100% |###############################| Time: 0:00:00   2.73 MB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00   2.93 MB/s
pip-9.0.1-py36 100% |###############################| Time: 0:00:00   2.78 MB/s
#
# To activate this environment, use:
# > activate pytraj3.6
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#

Building pytraj for Python 3.6
Traceback (most recent call last):
  File "scripts\build_wheel.py", line 243, in <module>
    builder.run()
  File "scripts\build_wheel.py", line 80, in run
    self.build_original_wheel(python_version)
  File "scripts\build_wheel.py", line 100, in build_original_wheel
    subprocess.check_call(cmlist)
  File "J:\amber-cmake\amber-install\miniconda\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "J:\amber-cmake\amber-install\miniconda\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "J:\amber-cmake\amber-install\miniconda\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "J:\amber-cmake\amber-install\miniconda\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Note that I had to remove `nomkl` from the list of packages to be installed because it doesn't seem to exist on Windows Miniconda 3.6.

**Comment by multiplemonomials** [comment]
## Issue 5: conversion of .pyx path to module name
This one is responsible for almost all of the issues I've had with pytraj from day 1:

In `base_setup.py`, in function `get_ext_modules()`:
```python
            # replace "/" by "." get module
            if "/" in ext_name:
                ext_name = ext_name.replace("/", ".")
```
should be
```python
            # replace "/" by "." get module
            if "/" in ext_name:
                ext_name = ext_name.replace("/", ".")
            
            # also replace backslashes on Windows
            if "\\" in ext_name:
                ext_name = ext_name.replace("\\", ".")
```

This was causing the `cannot export function PyInit_pytraj\analysis\c_action` errors!

**Comment by hainm** [comment]
> It's possible but it would be kind of ugly. Can't you just change cpptraj to pass a different DLL name to distutils on Windows?

Which part of pytraj code does that (It's been a while since I touch setup.py).
Just check here: pytraj use "cpptraj" for library. Do you mean it should use "cpptraj.lib" for windows?

https://github.com/Amber-MD/pytraj/blob/master/scripts/base_setup.py#L507

I tend to agree to whatever you do for Windows, so feel free to make a PR to pytraj repo. thanks.

**Comment by multiplemonomials** [comment]
## Issue 6: unistd.h
All of pytraj's Cython modules try to include `unistd.h`, and fail.  I had to grab a hacked-up Windows version off the Internet and put it in my include path to be able to build.

**Comment by hainm** [comment]
> Pytraj is putting libcpptraj.lib in its package, but the library it actually needs to install is libcpptraj.dll. To find it, you could use $CPPTRAJ_LIBDIR/../bin/libcpptraj.dll, or you could just have the user pass it as a another argument (CPPTRAJ_DLLDIR?).

uhm pytraj won't do this anymore. We really need to clean that code.

**Comment by multiplemonomials** [comment]
What I'm trying to say is that base_setup.py, line 511:
```
                libraries=['cpptraj'],
```
should be
```
                libraries=['libcpptraj'],
```
when building on Windows

**Comment by hainm** [comment]
> Issue 4: build_wheel.py

currently only works for Linux and MacOS. The overall aim is pack everything pytraj needs (especially libcpptraj.{so, dylib} and libnetcdf) so user just need "pip install pytraj", and everything just work magically.

For linux, pytraj use 'auditwheel': https://github.com/pypa/auditwheel
For MacOS, I wrote the script (based on `auditwheel` spirit).

**Comment by multiplemonomials** [comment]
Oh,  I took care to build my `libcpptraj.dll` so that all dependencies (netcdf and fftw) are statically linked in.  You don't have to include anything else)

**Comment by hainm** [comment]
> What I'm trying to say is that base_setup.py, line 511:

                 libraries=['cpptraj'],
> should be

 >                libraries=['libcpptraj'],
> when building on Windows

This could be done. thanks.
PS: Real code example like above always make thing easier :D

**Comment by multiplemonomials** [comment]
> Issue 3: pytraj DLL handling
I noticed that pytraj is printing this when building:
```
Copying J:\amber-cmake\msvc2015\cpptraj-install\lib\libcpptraj.lib to pytraj
```
It should be printing
```
Copying J:\amber-cmake\msvc2015\cpptraj-install\bin\libcpptraj.dll to pytraj
```

**Comment by hainm** [comment]
> Oh, I took care to build my libcpptraj.dll so that all dependencies (netcdf and fftw) are statically linked in. You don't have to include anything else)

I guess we still need to distribute libcpptraj.dll in standalone `pytraj` (uploaded to `pypi`), right?
If yes, how can you deal with PATH on Windows? On Linux and MacOS, pytraj use relative path to find `libcpptraj` so user does not need anything else just (`pip install`).

E.g: on MacOS, pytraj copy libcpptraj to pytraj/pytraj_3rd_party/ folder

https://github.com/Amber-MD/pytraj/blob/master/scripts/misc/fix_rpath_pip_osx.py#L75

**Comment by multiplemonomials** [comment]
Annoyingly, RPATH is not a thing on Windows.  `libcpptraj.dll` must be in your PATH when pytraj is imported.  That is the only requirement of the Windows version.

**Comment by multiplemonomials** [comment]
I am completely ignorant of how `pypi` works.  Should I send you the `.egg` file, or a `.tar.gz`?

**Comment by hainm** [comment]
> I am completely ignorant of how pypi works. Should I send you the .egg file, or a .tar.gz?

oh, I just mention about distribute pytraj via pypi (pip install). You don't need to send me or upload anything. (you already include egg.zip file. Just install Virtual machine on my mac).

**Comment by multiplemonomials** [comment]
Oh, that egg was built with CPython.  I just finished building a new one using Miniconda and with debugging information turned off.

The new .egg is [here](https://app.box.com/shared/static/0ierlrz2dqr5ypar9o58gm9yi4syvb2o.egg).  It needs [this libcpptraj.dll](https://app.box.com/shared/static/0ierlrz2dqr5ypar9o58gm9yi4syvb2o.egg).

**Comment by hainm** [comment]
> Issue 6: unistd.h

> All of pytraj's Cython modules try to include unistd.h, and fail. I had to grab a hacked-up Windows version off the Internet and put it in my include path to be able to build. Not sure if this is pytraj issue, or a cython one.

This is Window issue. :D Your way is the way people do. May we can include that file (what is it license?).

**Comment by multiplemonomials** [comment]
It's public domain.

**Comment by hainm** [comment]
Can you upload here so I can add to this PR?

https://github.com/Amber-MD/pytraj/pull/1419

**Comment by multiplemonomials** [comment]
[unistd.zip](https://github.com/Amber-MD/cmake-buildscripts/files/1220031/unistd.zip)

This probably goes without saying, but make sure that that file is only in the include path when building on Windows, not on Linux or Mac.

**Comment by multiplemonomials** [comment]
## Issue 8: installation of cpptraj headers
There needs to be a `INSTALL_HEADERS` option on the CMake build system that will install cpptraj's `.h` files to the install directory.  It's strange to point pytraj to the source directory in `INSTALL_HEADERDIR`.  I'll handle this fix.

**Comment by hainm** [comment]
> Issue 4: build_wheel.py

> After building and making a package with setup.py bdist, I tried to use your build_wheel.py script to create a wheel like you wanted, but it errored out and I have no idea why.

Just for clarity:

I normally do
```
python setup.py sdist # pack source code
python ./scripts/build_wheel.py dist/pytra*.gz
```

Here is build script that build everything: libcpptraj, pytraj for Linux and MacOS for pip, for conda with different python versions.
https://github.com/Amber-MD/pytraj/blob/master/devtools/builder/build_all.sh

**Comment by hainm** [comment]
> The new .egg is [here](https://app.box.com/shared/static/0ierlrz2dqr5ypar9o58gm9yi4syvb2o.egg).  It needs [this libcpptraj.dll](https://app.box.com/shared/static/0ierlrz2dqr5ypar9o58gm9yi4syvb2o.egg).

You uploaded wrong file for libcpptraj.

**Comment by multiplemonomials** [comment]
Oh whoops.  I fixed the link in the post.

**Comment by hainm** [comment]
Can you repack pytraj egg? The one you attach does not have cythonized binary files.

**Comment by multiplemonomials** [comment]
Sorry, but I'm moving in to USC on Monday, so my desktop with the files on it is packed away right now.  I'll send them to you by Monday night.

Should I have not used `setup.py bdist --format=egg`?  It seems like that command is broken somehow.  I guess I can just add the files to the egg using a find command and `p7zip`.

**Comment by hainm** [comment]
No worry. Enjoy moving. ;)
You can just zip whole built folder.

Hai

**Comment by multiplemonomials** [comment]
[Here you go](https://app.box.com/shared/static/ruj4aiof6fx5ij6i14qzsnen4p43sebk.zip)

**Comment by hainm** [comment]
Thanks.
