### ISSUE TITLE
Rename this repo "CMakeConfigScripts" to "cmake" (or so on)?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#3]
Ideally we should keep the same name in here (github) and in amber repo.

```bash
github: Amber-MD/CMakeConfigScripts
amber: amber/cmake
```

**Comment by multiplemonomials** [comment]
True, but "cmake" is kind of vague.  People might think we've forked the build system itself.  What about something like "cmake-scripts"?

**Comment by hainm** [comment]
sounds good. We need to change both here and in the amber repo. Or just keep change "amber/cmake" to "amber/CMakeConfigScripts".

**Comment by multiplemonomials** [comment]
@hainm Actually I do not have access to rename this repo.  Can you rename it to `cmake-buildscripts` when you get a chance?

**Comment by hainm** [comment]
done.
