### ISSUE TITLE
     /home/travis/amber16/dat    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#32]
Please see the log here:

https://travis-ci.org/Amber-MD/ambertools-ci/builds/275294394

(click "Raw log")

**Comment by hainm** [comment]
Just FYI, below is how I installed cmake v3.9
```

function install_ambertools_travis_cmake(){
    set -ex
    bash $HOME/amber$version/AmberTools/src/configure_python --prefix $HOME
    export PATH=$HOME/miniconda/bin:$PATH
    conda install cmake -c conda-forge -y
    mkdir -p $HOME/TMP/build
    mkdir -p $HOME/TMP/install
    cd $HOME/TMP/build
    cmake -DCOMPILER=gnu -DCMAKE_INSTALL_PREFIX=$HOME/TMP/install $HOME/amber$version
    make install
    cd $HOME/TMP/install && source amber.sh
}
```

**Comment by multiplemonomials** [comment]
Huh, neat, I didn't know conda could install CMake.  Nice.  I think the problem is that some things are missing from `mkrelease_at`.  I may have forgotten to commit the version I used.

**Comment by hainm** [comment]
>  Huh, neat, I didn't know conda could install CMake.

yeah, it could install anything as long as people build the packages.

**Comment by multiplemonomials** [comment]
I pushed a commit that should fix this.

**Comment by hainm** [comment]
thanks. running now: https://travis-ci.org/Amber-MD/ambertools-ci/builds/275315862

**Comment by hainm** [comment]
The install is ok now, just need to setup the (partial) test.
