### ISSUE TITLE
-DUSE_MINICONDA won't work if deleting build folder

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#37]
because Miniconda adds absolute path for some programs

e.g:
```
~/amber_git/install/miniconda/bin $ head conda
#!/Users/haichit/amber_git/build_gnu/CMakeFiles/miniconda/install/bin/python
if __name__ == '__main__':
    import sys
    import conda.cli

    sys.exit(conda.cli.main())
```

So either

- Post-process the shebang after making install 
- Or install miniconda directly to PREFIX first (vs make it in build folder).

**Comment by multiplemonomials** [comment]
Hmm yeah installing it to the prefix seems like a better option.  Thanks for bringing this to my attention, I hadn't even noticed this.  This is a large change so it might take a while to implement though.

**Comment by multiplemonomials** [comment]
Should be fixed now as of that commit
