### ISSUE TITLE
make -DCOMPILER values uppercase

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#39]
we have

`=FALSE`, `=LOCAL` but also have `=auto` and `=Release`

**Comment by multiplemonomials** [comment]
The `Release` one is a CMake convention, and it would be too hard to change it anyway since I have to find everywhere it's used.

I can make the values for `COMPILER` all-caps though.

**Comment by multiplemonomials** [comment]
Should be fixed by 2dd02c53
