### ISSUE TITLE
FindFFTW3 does not check for a certain header

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#42]
[CMakeError.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1308109/CMakeError.txt)

[CMakeOutput.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1308110/CMakeOutput.txt)

**Comment by multiplemonomials** [comment]
Can I have the make output please?

**Comment by hainm** [comment]
By the way, is there any simpler way to report the bug? Currently I need to rename the *.log to *.txt files, scp from casegroup to my desktop, attach here. (And you can see that I reported several issues).

**Comment by hainm** [comment]
> Can I have the make output please?

ok, let me rerun.

**Comment by hainm** [comment]
[log_make.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1308112/log_make.txt)

**Comment by multiplemonomials** [comment]
>By the way, is there any simpler way to report the bug? Currently I need to rename the *.log to *.txt files, scp from casegroup to my desktop, attach here. (And you can see that I reported several issues).

I suppose you could run something like this as standard for all errors:
```bash
cd <build dir>
cmake . >cmakeoutput.log 2>&1
make -j1 VERBOSE=1 >makeoutput.log 2>&1
tar cf errorreport.tar cmakeoutput.log makeoutput.log CMakeFiles/CMakeOutput.log CMakeFiles/CMakeError.log
scp errorreport.tar <wherever>
```

**Comment by multiplemonomials** [comment]
Sorry but I'm also going to need the console output of CMake for this one, since I can't tell from what I have whether this was using system or bundled fftw.

**Comment by hainm** [comment]
cmake ../amber

?

**Comment by multiplemonomials** [comment]
Yeah.  Interestingly enough, you can run `cmake .` as a shortcut to `cmake ../amber` in a build directory that you've already configured.

Or you could just run the commands I posted.

**Comment by hainm** [comment]
it used system fftw.

[log.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1309488/log.txt)

**Comment by multiplemonomials** [comment]
Well, your system fftw

**Comment by multiplemonomials** [comment]
I'll see about a check for that header.  It seems like it shouldn't have detected a fftw with no `fftw.f03`.

**Comment by hainm** [comment]
> Well, your system fftw seems broken then. Try -DFORCE_INTERNAL_LIBS=fftw.

I think this will work because we have been using it.

> I'll see about a check for that header. 

kool.

**Comment by hainm** [comment]
https://github.com/Amber-MD/cmake-buildscripts/issues/8#issuecomment-320662802

**Comment by hainm** [comment]
I think we should install interall fftw as default. Fortran is not that friendly.

**Comment by multiplemonomials** [comment]
FFTW is written in C, actually.  It has a Fortran compatibility interface, but no Fortran code, and no modules.    Hopefully once I fix his header, I'll be able to use the system version reliably.

**Comment by multiplemonomials** [comment]
Alright, this should be fixed now.  It should now reject your incomplete fftw3 installation automatically.  Let me know if you can confirm this.
