### ISSUE TITLE
In-source builds break everything

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#43]
I am pretty sure I messed up somewhere else ('cause the travis/circleci build ok).
Basically
```
cd $AMBERHOME
./configure --with-python python gnu
make install -j 4
```

give
```
$ make install -j 4
-- Starting configuration of Amber version 18.0.0...
-- CMake Version: 3.9.1
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- The Fortran compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
...
```

**Comment by hainm** [comment]
uhm,

I need to remove `cmake` installed via conda (in $HOME/miniconda/bin) and thing returns normal. Weird.

**Comment by hainm** [comment]
uhm, after removing that, things was fine until make cpptraj

```
make build_cpptraj
make[2]: Entering directory `/home/haichit/amber_git/amber/AmberTools/src'
(cd cpptraj && make install)
make[3]: Entering directory `/home/haichit/amber_git/amber/AmberTools/src/cpptraj'
/bin/sh: /home/haichit/miniconda3/bin/cmake: No such file or directory
make[3]: *** [cmake_check_build_system] Error 127
make[3]: Leaving directory `/home/haichit/amber_git/amber/AmberTools/src/cpptraj'
make[2]: *** [build_cpptraj] Error 2
make[2]: Leaving directory `/home/haichit/amber_git/amber/AmberTools/src'
make[1]: *** [serial] Error 2
make[1]: Leaving directory `/home/haichit/amber_git/amber/AmberTools/src'
make: *** [install] Error 2
```

**Comment by multiplemonomials** [comment]
Did you build inside the source tree?  That isn't supported and probably overwrote some or all of Amber's makefiles with CMake ones.  Try hard-resetting Amber and all submodules to git HEAD.  

I should probably put a warning about that on the wiki somewhere, huh.

**Comment by hainm** [comment]
Overwrite stuff is cmake or is because you make that way? What if user use the release tarfile and accidentally do that? it's hard for them to undo.

**Comment by hainm** [comment]
or at least quit the process if running in source code.

**Comment by multiplemonomials** [comment]
It's a CMake issue, yeah.  I'll make it so it will error out if you try to do an in-source build, good idea.
