### ISSUE TITLE
-DUSE_MINICONDA=True -DPYTHON_EXECUTABLE=python

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#44]
how do you deal with double options? Current behaviour is to download Miniconda.

**Comment by multiplemonomials** [comment]
Yeah, USE_MINICONDA overrides the python executable selection.  That seems like how we want it to work, right?

**Comment by multiplemonomials** [comment]
There aren't a lot of places where there are double options, but where there are, I don't really have a general policy of dealing with them.

**Comment by hainm** [comment]
Ok that's good to know you know that.

**Comment by multiplemonomials** [comment]
So, can I close this, or is there still an issue? :)

**Comment by hainm** [comment]
Yeah please close it.

**Comment by hainm** [comment]
I reopen this issue since below command won't work as expected:

```
$HOME/programs/cmake-3.9.4/bin/cmake \
    -DPRINT_PACKAGING_REPORT=TRUE \
    -DCMAKE_INSTALL_PREFIX=../install \
    -DPYTHON_EXECUTABLE=$HOME/miniconda3/bin/python \
    ../amber
```

In this case, requiring to add `-DUSE_MINICONDA=False` seems not a correct way.

**Comment by multiplemonomials** [comment]
Why did you reopen this?

**Comment by hainm** [comment]
check the post before your post.

**Comment by multiplemonomials** [comment]
Oh whoops.

Regarding your post, I feel like this is correct behavior.  Even though you are telling Amber to use a Miniconda interpereter, it's still an external Python that Amber isn't supposed to use without being explicitly told to.  `USE_MINICONDA` specifically means to download and use an internal Miniconda.

**Comment by hainm** [comment]
yeah, you're right about "expected", because the original default of USE_MINICONDA is False.
However, in practice, the new behaviour does not match to `./configure`. 

```
-DPYTHON_EXECUTABLE=$HOME/miniconda3/bin/python \
-DUSE_MINICONDA=False 
```

How's about the default of -DUSE_MINICONDA=auto?

**Comment by hainm** [comment]
```
./configure --with-python `which python` # use whatever python found
./configure gnu # download (with asking) Miniconda
```

**Comment by hainm** [comment]
btw, we should try to keep similar interface with old one, unless we have strong reason to change.

**Comment by multiplemonomials** [comment]
Okay, so you're saying that:

If the user specifies `PYTHON_EXECUTABLE` on the first run, then `USE_MINICONDA` should be set to false.  If they specify `USE_MINCIONDA=FALSE`, then it will automatically look for a `PYTHON_EXECUTABLE`, and use that.  If neither, it will default to using miniconda.

This is correct, right?

I was thinking that maybe we should do something different.  What if I made a new option `PYTHON_INTERP` with 3 values: `SYSTEM`, `MINICONDA`, and `DISABLE`?  I would get rid of `USE_MINICONDA`, and the user would have to pass a value for `PYTHON_INTERP` for the build to continue.

What do you think about that?

**Comment by hainm** [comment]
> This is correct, right?

so here is what I am thinking about (similar to non-cmake).

1. 
```
cmake amber -DCMAKE_INSTALL_PREFIX=prefix
```

In this case, we should prefer to use miniconda.
- check if having prefix/miniconda: If yes, use python in that folder
- if not: download and install it

2.

```
cmake amber -DCMAKE_INSTALL_PREFIX=prefix -DPYTHON_EXECUTABLE=/path/to/python
-> use that `path/to/python`
```

I know the behaviour is a bit different from what you are expecting but we don't really want to support and maintain a bunch of options.

**Comment by multiplemonomials** [comment]
OK, I have changed this behavior again.  What we had didn't make sense with the new Anaconda support.

If `conda` is detected on your system, it will use Anaconda's interpreter, and print this message:
```
Found system Anaconda at /home/jamie/anaconda3.  It will be used as a Python interpereter, and for                                                                                                    additional shared libraries.  It is not possible to avoid using Anaconda if it is on the PATH.  To build Amber without using Anaconda, remove it from your PATH.  To use a different Anaconda install, just move it to the front of your PATH and rerun CMake.  To change the Python interpreter in use to a different one inside Anaconda, set the PYTHON_EXECUTABLE variable to point to it.
```

Otherwise, it will stop the build and give the user a choice:
```
We highly recommend letting AMBER install a Python environment with all prerequisites inside 
its install location via a Continuum Miniconda distribution. 
Miniconda is chosen because it comes with a great package manager conda, which is 
specially designed for numerical and scientific computing. This makes compiling 
AMBER Python extensions much easier. 
This will only need to be done once. 
It may take several minutes and downloads around a hundred megabytes of data. 

Config variable DOWNLOAD_MINICONDA has been autoset to TRUE.  To accept and download Miniconda, just run cmake again. 
If you do not want to download Miniconda, run cmake again with DOWNLOAD_MINICONDA set to FALSE.
```

I think you've already spotted this change, but here's what it's supposed to do

**Comment by multiplemonomials** [comment]
This change also has the upside of allowing the updater to work using the built-in Miniconda, which wasn't possible before AFAIK.

**Comment by multiplemonomials** [comment]
Is it alright if I close this issue now?  @hainm are you OK with the current behavior or do you still think it needs changes?

**Comment by hainm** [comment]
Yes please close it. Thanks.
