### ISSUE TITLE
-DPYTHON_EXECUTABLE=something and "something" not found

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#46]
if "something" not found, cmake should stop and let user fix that rather silently turn Python OFF.

```
-- Build Python Programs:  OFF 
```

**Comment by hainm** [comment]
What's status of this issue? Rejected or accepted. :d

**Comment by multiplemonomials** [comment]
I have made it work like you asked.  Should've probably mentioned that, huh.

**Comment by hainm** [comment]
Thanks.
