### ISSUE TITLE
what's policy to find readline? 

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#47]
I saw
```
Found Readline: /home/haichit/miniconda3/include 
```

based on $PATH?

**Comment by multiplemonomials** [comment]
CMake just looks for it everywhere it can on your system.  That probably includes your PATH, yeah, along with `/usr`,  `/usr/local`, and the 
CMake variable `CMAKE_PREFIX_PATH`

**Comment by hainm** [comment]
thanks
