### ISSUE TITLE
add information about install folder?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#49]
hi

This is what I saw after "cmake ../amber"
```
[...]
-- Build files have been written to: /Users/haichit/amber_git/build_gnu
```

Can we add
```
-- Package will be installed to: bla bla
(or so on)
```

**Comment by multiplemonomials** [comment]
That's already in the build report, just scroll up a bit.

**Comment by hainm** [comment]
I see. Can you make it the last line too. Normally we do that to remind user about important info.

**Comment by multiplemonomials** [comment]
I just committed this to Amber master.  I just copied the message out of `configure2`. Can you tell me what you think?

**Comment by hainm** [comment]
> $amberhome/amber.sh

should this be absolute path rather a variable?

>(You need to do the above before running 'make install')

Not True for cmake, right?

> The next step is to run "make", then "make install"

I always do "make install" without "make". Why do users really need to do that?

**Comment by hainm** [comment]
Are you considering to suggest user to source amber.sh (and so on) in the final message of "make install" rather the "cmake amber"?

**Comment by multiplemonomials** [comment]
> should this be absolute path rather a variable?
>Not True for cmake, right?
Oh whoops.  I'll fix those.  Good catch.

> I always do "make install" without "make". Why do users really need to do that?

You can do it either way, it doesn't make a difference in the build.  However, if you're installing to a write-protected location, you need to only run the installation with `sudo`, not the build, so as to not get yourself in a permissions mess.

**Comment by hainm** [comment]
if possible, we just keep the original behaviour (run configure and "make install") if there is not compelling reason to add one more step.

> However, if you're installing to a write-protected location, you need to only run the installation with sudo, not the build, so as to not get yourself in a permissions mess.

I think this is because cmake is trying to install amber to /usr/local.
And we don't encourage users to use sudo.

**Comment by multiplemonomials** [comment]
Oh, OK.  I'll recombine it.

**Comment by multiplemonomials** [comment]
This is working correctly now, right @hainm ?

**Comment by hainm** [comment]
yeah thanks.
