### ISSUE TITLE
command help?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#5]
Jamie,

does your setup allow "cmake ../amber -h" (tried but only see non-amber stuff) that behaves similar to ./configure -h (non-cmake)?

**Comment by multiplemonomials** [comment]
Sort of.  You can see all of the options and their descriptions by using the command `ccmake` in place of `cmake` if it's supported on your platform.  You can also use the `cmake-gui` tool for a graphical interface (hover over each variable to see its documentation).

These views can be a bit cluttered with extra stuff, however, so I made [this guide on the wiki](http://ambermd.org/pmwiki/pmwiki.php/Main/CMake-Common-Options) which covers most of the options you'd want to use.
