### ISSUE TITLE
Change: CMAKE_INSTALL_PREFIX --> INSTALL_PREFIX

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#50]
what do you think?

**Comment by hainm** [comment]
after reading your post [here](https://github.com/Amber-MD/cmake-buildscripts/issues/48#issuecomment-331611831), seems like we can not change it?

**Comment by multiplemonomials** [comment]
We can change it, as far as I know.  I can override CMake's default with a new default.

**Comment by hainm** [comment]
uhm, I think we should still keep `CMAKE_INSTALL_PREFIX` to make it consistent with other non-amber packages.

**Comment by multiplemonomials** [comment]
Yeah, I agree.
