### ISSUE TITLE
AmberTools/src/leap/src/Wc/CMakeFiles/wcleap.dir/WcActCB.c.o] Error 1

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#51]
Please see the build log here (click "Raw log"); and that's all I have.
cheers.

https://travis-ci.org/Amber-MD/ambertools-ci/jobs/279108133

PS: all the cmake stuff is after the line "-- Miniconda install successful!"

**Comment by multiplemonomials** [comment]
As a side note, do you realize that the CI script is downloading miniconda twice, once through CMake and once through your Python script?  It is kind of a waste of space and time.  You can probably pass the `-DUSE_MINICONDA=FALSE -DPYTHON_EXECUTABLE=<python executable from the conda environment you already downloaded>` argument to CMake and speed up your builds a bit.

**Comment by multiplemonomials** [comment]
hmm this seems to have been seen a few times before: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=393026

**Comment by multiplemonomials** [comment]
Did previous builds with the same configuration succeed?

**Comment by multiplemonomials** [comment]
If it just popped up randomly, maybe the X11 headers are just broken on that particular Travis build machine.

**Comment by hainm** [comment]
I am not sure, but non-cmake build is alright.

And thanks for the tips about double install of miniconda.

**Comment by hainm** [comment]
> I am not sure, but non-cmake build is alright.

See "nightly" and "ightly-many-osx" branches.
 https://travis-ci.org/Amber-MD/ambertools-ci/branches

**Comment by multiplemonomials** [comment]
Yeah, my theory is that there's one particular Travis worker with broken X11 headers.

**Comment by multiplemonomials** [comment]
...because the other `TEST_TASK=fast` job, which ran at the same time with the same CMake options, built fine.

**Comment by multiplemonomials** [comment]
Is it ok to just pass the `cmake -DBUILD_GUI=FALSE` option to turn off XLeap, since the CI doesn't test it anyway?

**Comment by hainm** [comment]
yeah will do.

**Comment by multiplemonomials** [comment]
So, can I close this, or do we still need to figure it out?

**Comment by hainm** [comment]
hold on. The build is not green yet.

**Comment by multiplemonomials** [comment]
Oh, by the way, I got Windows CI working yesterday.  Check out http://www.jasonswails.com:8888/job/Amber/job/AmberWindows/

**Comment by hainm** [comment]
The question is: why non-cmake does not fail with X11?

**Comment by hainm** [comment]
> Oh, by the way, I got Windows CI working finally. Check out 

kool.

**Comment by hainm** [comment]
> Miniconda can't fit in a Windows installer because it's over the 1GB limit

I think it's very easy for user to install it by themself.

**Comment by multiplemonomials** [comment]
Yeah.  Are Python programs built against Miniconda compatible with CPython?

**Comment by hainm** [comment]
What do you mean about "CPython?"?

As far as I know, Miniconda is the most popular Python distribution and its conda is very popular too.

**Comment by multiplemonomials** [comment]
CPython is the official name of the "default" Python distribution.   See [here](https://en.wikipedia.org/wiki/CPython)

**Comment by hainm** [comment]
> CPython is the official name of the "default" Python distribution. See here

so I have never tested amber with this. :D 

by the way, using `-DBUILD_GUI=FALSE` does help. Thanks. Still need to figure out to run the test.
