### ISSUE TITLE
OS X package needs to fix the install_names of bundled libraries

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#53]
If we're distributing the binary on MacOS, we still need to include gfortran related. 

Here is the [script](https://github.com/Amber-MD/ambertools-binary-build/blob/master/conda_tools/update_gfortran_libs_osx.py) I made for non-cmake build, just give you some ideas.
Basically, the script copy 
```
    'libstdc++.6.dylib', 'libgfortran.3.dylib', 'libgcc_s.1.dylib',
    'libquadmath.0.dylib'
```
from /usr/local/gfortran/lib to $AMBERHOME/lib/amber_3rd_party and do a bunch rpath and loader_path fixing.

Below is an example after fixing
```
$ otool -L amber17/bin/cpptraj 
amber17/bin/cpptraj:
	@rpath/libfftw3.3.dylib (compatibility version 7.0.0, current version 7.0.0)
	@rpath/amber_3rd_party/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	@rpath/libsander.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/amber_3rd_party/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.22.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	@rpath/amber_3rd_party/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by hainm** [comment]
The idea is if user only need to download amber binary and things just work.

**Comment by multiplemonomials** [comment]
I am attempting to do this using CMake's `BundleUtilities` module, which does essentially the same thing as your script.  I'll let you know whether that works or not in a few days.

**Comment by multiplemonomials** [comment]
Hmm, looking into this further, I might have to use that script.  This is going to be such a huge project...

**Comment by multiplemonomials** [comment]
Alright, I finally got a working derivative of your script incorporated into CMake.  It doesn't just do libgfortran; it's able to recursively find and bundle all dependency libraries of all Amber executables and libraries!
