### ISSUE TITLE
CMake ends up incorrectly linking to Miniconda's shared libraries when it's in the PATH

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#56]
Please see attached file (tar xf repor_linux.txt)

[report_linux.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1331465/report_linux.txt)

**Comment by multiplemonomials** [comment]
Can you please post the output of `nm /home/haichit/miniconda3/lib/libncurses.so` for me?

**Comment by multiplemonomials** [comment]
In the command prompt that you use to invoke CMake, can you please run `( set -o posix ; set ) | less`?  I want to figure out why CMake is looking in Miniconda for libraries.

**Comment by hainm** [comment]
here we go.

[log_libncurses.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1333280/log_libncurses.txt)

[log_posix.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1333281/log_posix.txt)

**Comment by multiplemonomials** [comment]
Yep, as it turns out, CMake is finding `/home/haichit/miniconda3/lib` from your `PATH`, and that contains a bad `libncurses.dylib`.  Unfortunately there is no easy way to stop CMake from searching your PATH for libraries, so what you'll have to do is move `/home/haichit/miniconda3/bin` to the end of your PATH (after `/usr/bin`), and then delete your build directory and reconfigure.

**Comment by hainm** [comment]
I dont thin that is desire since I (user) want to us python from miniconda.

Would be geat if you can fix that. Thanks

**Comment by multiplemonomials** [comment]
OK, I'll see about a patch sometime this week.  There is a way to fix this but it's a huge pain; I have to change every single `find_library()` function call.  CMake needs to fix this...

**Comment by hainm** [comment]
Post here for record
```
Scanning dependencies of target cpptraj
[ 80%] Building CXX object AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/Action_Esander.cpp.o
[ 80%] Building CXX object AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/Command.cpp.o
[ 80%] Building CXX object AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/Cpptraj.cpp.o
[ 80%] Building CXX object AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/Energy_Sander.cpp.o
[ 80%] Building CXX object AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/ReadLine.cpp.o
[ 80%] Building CXX object AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/main.cpp.o
[ 80%] Linking CXX executable cpptraj
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `tgetnum'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `tgetent'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `tgetstr'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `tgoto'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `UP'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `BC'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `tputs'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `PC'
/home/haichit/miniconda3/lib/libreadline.so: undefined reference to `tgetflag'
collect2: ld returned 1 exit status
make[2]: *** [AmberTools/src/cpptraj/src/cpptraj] Error 1
make[1]: *** [AmberTools/src/cpptraj/src/CMakeFiles/cpptraj.dir/all] Error 2
make: *** [all] Error 2
                                  
```

**Comment by multiplemonomials** [comment]
Hmm looks like others are having the same problem: https://github.com/pism/pism/issues/356

I just pushed commit 9e046b8e which tries to fix this.  Otherwise, you might have to use that guy's workaround, because there's nothing else I can do on the CMake side.

**Comment by hainm** [comment]
uhm, if you look as an user's perspective: if non-cmake works fine while cmake won't work, why we recommend them to use it? 

As you see even I myself was getting lots of issues (yeah, you resolved them) with building using cmake, non-experienced users will get similar issues too.

**Comment by hainm** [comment]
any solution by adding flag to cmake?

**Comment by multiplemonomials** [comment]
So, did you try the latest `cmake-buildscripts` master, and it's still broken?

Anyway in my opinion this is Miniconda's fault, not mine.  They take broken and incomplete versions of system libraries, and put them on the PATH instead of in some other folder, it _is_ going to break things.

And yeah, the cmake stuff is a beta/experimental version.  I'm working on fixing things as people report them, hopefully by the next release it'll be as stable as the Makefile build system.

**Comment by hainm** [comment]
Yeah still broken.

Btw, I am not saying your fault. Just saying about solution, given we are living in ecosystem that we can not control.

**Comment by hainm** [comment]
Uhm, only try the one you pushed to amber.

**Comment by multiplemonomials** [comment]
I suppose there is one other thing I could do.  I could have CMake remove all directories containing the phrase "conda" from its own `PATH` variable (after searching for Python of course).  Think that would work?  Does anaconda/miniconda always get installed to a folder named anaconda or miniconda?

**Comment by multiplemonomials** [comment]
Also, do you mind trying the workaround mentioned in that issue?  Does it work?  I'm not saying that users will use that, I'm just trying to narrow down the problem. Thanks.

**Comment by hainm** [comment]
I will try tonight. (read your comment last night so don't have a chance to try it).

**Comment by hainm** [comment]
> I suppose there is one other thing I could do. I could have CMake remove all directories containing the phrase "conda" from its own PATH variable (after searching for Python of course).

check if {prefix}/bin/ has "conda" program.

**Comment by hainm** [comment]
that's what we check in configure2 (or configure_python, not sure).

**Comment by hainm** [comment]
> Also, do you mind trying the workaround mentioned in that issue? Does it work? 

no, every try gets new error. see attach (rename .txt -> .tar)

[errorreport.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1364206/errorreport.txt)

In short:
```
-- Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY)
-- Cannot use internal readline because its dependency (libtermcap/libncurses) was not found.  Set TERMCAP_LIBRARY and TERMCAP_INCLUDE_DIR to point to it.
```

Note that non-cmake build is fine. Enjoy.

**Comment by hainm** [comment]
by the way, you really need to to setup the CI on travis to make sure it works with fresh environment. I see many similar errors from there with my local build.

**Comment by multiplemonomials** [comment]
Oh this a known & easily fixed issue; I just have to submit a PR to cpptraj to change one line of CMake code.   I'll try to do that by Tuesday.

As a workaround, you can install libncurses through brew/macports, and it will be able to build internal readline and the issue will be fixed.

**Comment by multiplemonomials** [comment]
I accidentally broke the `-DNO_READLINE` definition for cpptraj in the experimental-branch changes.

**Comment by hainm** [comment]
> you can install libncurses through brew/macports

I have no issue with mac build (and the build on travis is ok too). :D

**Comment by hainm** [comment]
> I accidentally broke the -DNO_READLINE definition for cpptraj in the experimental-branch changes.

can you post the change here so I can try?

**Comment by multiplemonomials** [comment]
Not at the moment I'm afraid, I'm on a trip until Sunday night.  I'll post it then though.

**Comment by hainm** [comment]
ah, ok. Enjoy.

**Comment by multiplemonomials** [comment]
Of course, the same workaround applies to any system it's broken on.  Apply the Miniconda workaround, install `libncurses`, and you should be good to go.

Also I think I mentioned it before but I'm currently using Jason's Jenkins instance as my main CI and buildserver.  Check it out, I've got automatic builds of Mac, Linux, and Windows going.  I will try to fix Travis when I have time, but it's way less convenient than Jenkins because it's dependent on commits to trigger & change builds.

**Comment by hainm** [comment]
>  install libncurses, and you should be good to go.

it's easy if it's my computer but I am using casegroup cluster.
(I could try with docker image on my Mac but it's very slow to compile amber).

> Check it out, I've got automatic builds of Mac, Linux, and Windows going. 

yeah, then forgot about travis then. I am using travis because I can run 5 concurrent jobs.

**Comment by multiplemonomials** [comment]
Plus Jenkins doesn't have a time limit so I can run the full test suite every night, and I can build on all 3 OSs simultaneously.

OK I went and found the broken line in cpptraj.  The fix is, in `AmberTools/src/cpptraj/src/CMakeLists.txt`, change line 161 to:
```cmake
target_compile_definitions(cpptraj PRIVATE USE_SANDERLIB)
```

**Comment by hainm** [comment]
dont want to ruin your vacation, but did not work. :D

**Comment by multiplemonomials** [comment]
Do you mind sending me another error report for this new error?

**Comment by multiplemonomials** [comment]
...or is it the same error?

**Comment by hainm** [comment]
yeah the same.

**Comment by multiplemonomials** [comment]
huh

**Comment by multiplemonomials** [comment]
I'll work on it some more later I guess

**Comment by hainm** [comment]
I will try to reproduce it tonight, to make sure ...

**Comment by hainm** [comment]
> AmberTools/src/cpptraj/src/CMakeLists.txt, change line 161 to:

What's exact line 161? mine is 
`set_property(TARGET cpptraj PROPERTY COMPILE_DEFINITIONS USE_SANDERLIB)`

**Comment by hainm** [comment]
uhm, I  think replacing the line 161 does help.

Previously I made mistake by changing line 121.

**Comment by hainm** [comment]
> Otherwise, you might have to use that guy's workaround

Yes, the work around is working now.

```
export PATH=/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:
/usr/sbin:/sbin:$HOME/miniconda3/bin
```

**Comment by multiplemonomials** [comment]
Awesome!  Now I just have to get those fixes into the actual codebase.

**Comment by hainm** [comment]
I am getting some insights about this. Will post shortly.

**Comment by hainm** [comment]
ok, so turns out that if I am using cmake in miniconda/bin (installed from conda-forge channel), build fails even if putting miniconda path in the end.

I built cmake by myself and use that, always work nicely. 
Any idea why? cmake try to use lib in its installed folder first?

**Comment by multiplemonomials** [comment]
Wait, but what if you _use_ the CMake you built from source, but _don't use_ the Conda `PATH` workaround?  Does it work then?

**Comment by multiplemonomials** [comment]
When I get a chance, I'll investigate how CMake gets its default include paths

**Comment by hainm** [comment]
Yes, it works in both case "do" and "do NOT" use conda path.

**Comment by multiplemonomials** [comment]
So for now, I guess the workaround is to not use Conda CMake.  Great job, thanks for the help figuring this out!

**Comment by hainm** [comment]
>  I guess the workaround is to not use Conda CMake. 

So now I need to figure out how to get cmake on travis.

(with conda, just "`conda install cmake -c conda-forge`)

**Comment by hainm** [comment]
If I tried to force to use internal readline,

```
CMake Error at AmberTools/src/readline/CMakeLists.txt:34 (message):
  Internal readline is being used, but its dependency, termcap, was not
  found.  Please install it.  On linux, a termcap interface is usually
  provided by ncurses.
```

**Comment by multiplemonomials** [comment]
Yeah it's supposed to give that error.  Install libncurses for it to work.

**Comment by hainm** [comment]
ha ha, it would be easy if having conda, because liubcurses is there too.

```
~/miniconda3 $ find_files *libncurses*
./lib/libncurses++.a
./lib/libncursesw.so.5.9
./lib/libncurses.so.5.9
./lib/libncurses++w.a
./lib/libncurses.a
./lib/libncursesw.a
./pkgs/ncurses-5.9-10/lib/libncurses++.a
./pkgs/ncurses-5.9-10/lib/libncursesw.so.5.9
./pkgs/ncurses-5.9-10/lib/libncurses.so.5.9
./pkgs/ncurses-5.9-10/lib/libncurses++w.a
./pkgs/ncurses-5.9-10/lib/libncurses.a
```

(previous error is when I was using my own built cmake).

**Comment by hainm** [comment]
btw, if you can figure out why conda's cmake won't work and have a fix for that, it would be super help.

**Comment by multiplemonomials** [comment]
I figured out how to get CMake on Travis with my CI setup:
```sh
sudo add-apt-repository -y "ppa:george-edison55/precise-backports"
sudo apt-get update
# for SOME REASON, on Travis, emacs-common conflicts with cmake 3, and the following command will also cause emacs-common to get removed.
sudo apt-get -y install --only-upgrade cmake cmake-data
```

**Comment by multiplemonomials** [comment]
OK I'm going to split this into 2 different issues.

**Comment by hainm** [comment]
yeah. thanks.

**Comment by multiplemonomials** [comment]
Actually, I just realized that you weren't saying that libncurses detection is broken.  
Created new issue for revised problem: #67.

**Comment by hainm** [comment]
> I just realized that you weren't saying that libncurses detection is broken.

In the broken case, I was using my own cmake.
In non-broken case, I was using cmake from miniconda, which already has libncurses.

**Comment by multiplemonomials** [comment]
Wait, but you are saying that it isn't finding the `libncurses` inside Miniconda, right?

**Comment by hainm** [comment]
yeah, it can not find libncurses inside Miniconda.
(may be because LD_LIBRARY_PATH is not set to that? only conda PATH is added).

**Comment by multiplemonomials** [comment]
Yes, I explicitly disabled this in a recent commit, because we don't _want_ to find that library.   It's broken; it's missing important symbols.

You can define the variable `TERMCAP_LIBRARY` to point to it if you want to force CMake to use it.

**Comment by hainm** [comment]
be the way,

- cmake from conda-forge works fine on MacOS.
- For linux, I have the binary
```
        curl https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.sh -O
        bash cmake-3.9.4-Linux-x86_64.sh --prefix=$HOME/cmake_install --skip-license
        export PATH=$HOME/cmake_install/bin:$PATH
```

**Comment by hainm** [comment]
> For linux, I have the binary (work fine locally, have not tested on travis yet).

works fine on travis too. (still figure out some error related to install path due to my setup). Anyway, first time I can make it installable on travis for Linux build. lol.

**Comment by Ritu-parna98** [comment]
I am having the same issue. After uninstalling cmake, when I reinstalled cmake, it again took the path inside anaconda. Here is the output:
(base) [565]Rituparna[~] which cmake
/home/rituparna/anaconda3/bin/cmake

How did you resolve the issue finally? 

About my local machine:
(base) [554]Rituparna[~] uname -a
Linux rituparna-Inspiron-5567 4.4.0-198-generic #230-Ubuntu SMP Sat Nov 28 01:30:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(base) [555]Rituparna[~] lsb_release -a
LSB Version: core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description: Ubuntu 16.04.7 LTS
Release: 16.04
Codename: xenial

**Comment by multiplemonomials** [comment]
I think the fix is to have your conda env deactivated whenever you run cmake.  And if you already have build directories that had been configured with the conda env active, you have to delete them and start over.

**Comment by Ritu-parna98** [comment]
Thanks for your answer. This worked for me. I commented out all the paths related to anaconda in Bashrc and then cmake took the right path.
