### ISSUE TITLE
PY_INTERP_FOR_HAVE_NUMPY confusion

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#58]
Hi, 

So I am not clear about the message below
```
PY_INTERP_FOR_HAVE_NUMPY: /root/miniconda3/bin/python
PY_INTERP_FOR_HAVE_SCIPY: /root/miniconda3/bin/python
PY_INTERP_FOR_HAVE_MATPLOTLIB: /root/miniconda3/bin/python
PY_INTERP_FOR_HAVE_CYTHON: /root/miniconda3/bin/python
PY_INTERP_FOR_HAVE_TKINTER: /root/miniconda3/bin/python
PY_INTERP_FOR_HAVE_TKINTER: /root/miniconda3/bin/python
PY_INTERP_FOR_HAVE_DISTUTILS_SYSCONFIG: /root/miniconda3/bin/python
```

This would make user think that we are checking multiple python versions and for each import testing, we pick the working one.

**Comment by multiplemonomials** [comment]
Oh, sorry, this is debugging code that got left in by accident.  I'll get rid of it soon.  

Did you `git pull origin master` in the `cmake` submodule?  Because that's a bit broken right now.

**Comment by hainm** [comment]
> Did you git pull origin master in the cmake submodule?

No, only do `git submodule update`.

**Comment by multiplemonomials** [comment]
Huh, I'm not sure how that code made it to master.   This whole "separate CMake branch"  business has been quite an ordeal.

**Comment by hainm** [comment]
uhm, may be I did that but forgot.

**Comment by hainm** [comment]
just did `git submodule foreach git checkout .`

```
-- Python version 3.6 -- OK
PY_INTERP_FOR_HAVE_NUMPY: 
Checking for Python package numpy -- found
PY_INTERP_FOR_HAVE_SCIPY: 
Checking for Python package scipy -- found
PY_INTERP_FOR_HAVE_MATPLOTLIB: 
Checking for Python package matplotlib -- found
PY_INTERP_FOR_HAVE_CYTHON: 
Checking for Python package cython -- found
PY_INTERP_FOR_HAVE_TKINTER: 
Checking for Python package tkinter -- found
PY_INTERP_FOR_HAVE_TKINTER: /Users/haichit/miniconda3/bin/python
PY_INTERP_FOR_HAVE_DISTUTILS_SYSCONFIG: 
```

seems ok.

**Comment by multiplemonomials** [comment]
Should be fixed as of merge of experimental branch.
