### ISSUE TITLE
Some systems have /lib64/... PYTHONPATHs

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#61]
Hey @hainm, I'm getting this error off of Jason's Jenkins machine. 

```
You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/cmake//lib64/python3.4/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/iscratch/jenkins/jenkins/jenkins/home/workspace/Amber/amber-ci-install/cmake/lib/python3.4/site-packages'
```

I didn't even know this was possible.  Do you know how I can detect systems where PYTHONPATH uses `lib64` instead of `lib`?

**Comment by hainm** [comment]
it's odd. I've never seen that.

We need to do google search in this case.

**Comment by hainm** [comment]
or I think you can add that lib64 to python path too.

**Comment by multiplemonomials** [comment]
Well, it turns out that my fix didn't work.  It seems like it is almost impossible to get the relative `site-packages` directory path on all platforms.  The best I've gotten is 
```python
import sys; 
from distutils.command.install import INSTALL_SCHEMES; 
print(INSTALL_SCHEMES['unix_prefix']['purelib'].replace('$py_version_short', (str.split(sys.version))[0][0:3]).replace('$base/', ''))'
```
On Jason's CI machine, this correctly prints:
````
lib64/python3.4/site-packages
````

I'm wondering if there isn't an easier way to do this.  The error message from the install tells me to use the [PYTHONUSERBASE](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE) environment variable to redirect the install to the Amber prefix.  @hainm Do you know if this will work?

**Comment by hainm** [comment]
I have never tried that. Have you tried my suggestion yet?

> or I think you can add that lib64 to python path too.

Basically add both lib and lib64.

**Comment by hainm** [comment]
https://stackoverflow.com/questions/39682688/how-to-set-pythonpath-to-multiple-folders

**Comment by hainm** [comment]
need to update amber.sh too, something like

`
export PYTHONPATH="${AMBERHOME}/lib/python3.6/site-packages:${AMBERHOME}/lib64/python3.6/site-packages:${PYTHONPATH}"
`

**Comment by multiplemonomials** [comment]
This is finallly working with the most recent iteration of the fix.

**Comment by hainm** [comment]
your change actually broke multi-python builds

[log.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1464108/log.txt)

```
time cmake \
    -DPRINT_PACKAGING_REPORT=TRUE \
    -DPYTHON_EXECUTABLE=$HOME/miniconda3/envs/py2/bin/python \
    -DUSE_MINICONDA=False \
    -DCMAKE_INSTALL_PREFIX=/Users/haichit/amber_git/cmake-reports/install-multi-pythons \
    $HOME/amber_git/amber

time make install -j 4

time cmake \
    -DPYTHON_EXECUTABLE=$HOME/miniconda3/bin/python \
    -DUSE_MINICONDA=False \
    -DCMAKE_INSTALL_PREFIX=/Users/haichit/amber_git/cmake-reports/install-multi-pythons \
    $HOME/amber_git/amber

time make install -j 4

```

**Comment by hainm** [comment]
```

Please make the appropriate changes for your system and try again.
running build
running build_py
running install
Checking .pth file support in /Users/haichit/amber_git/cmake-reports/install-multi-pythons//lib/python3.6/site-packages/
/Users/haichit/miniconda3/bin/python -E -c pass
TEST FAILED: /Users/haichit/amber_git/cmake-reports/install-multi-pythons//lib/python3.6/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/haichit/amber_git/cmake-reports/install-multi-pythons//lib/python3.6/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/Users/haichit/amber_git/cmake-reports/install-multi-pythons/lib/python2.7/site-packages'
```

**Comment by multiplemonomials** [comment]
What's a "multi-python build"?

**Comment by multiplemonomials** [comment]
Oh wait, I see the problem.  I just need to re-scan this when PYTHON_EXECUTABLE changes.

**Comment by multiplemonomials** [comment]
Check has been added!  It should be working now.
