### ISSUE TITLE
cmake build failed after your merge today

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#64]
Here is the working version few days ago:  https://travis-ci.org/Amber-MD/ambertools-ci/jobs/282096145
    - install is ok
    - python test fail (known issue due to PYTHONPATH)

Here is non-working version: https://travis-ci.org/Amber-MD/ambertools-ci/jobs/282505551

**Comment by multiplemonomials** [comment]
Looks like a bunch of CMakeLists.txt are missing from the source tree.  I suspect that something is wrong with `mkrelease_at`.  I'll check it tomorrow, I'm busy for the rest of today.

**Comment by multiplemonomials** [comment]
Let's see if the commit I just pushed fixes this...

**Comment by multiplemonomials** [comment]
Yup, seems to be working; it gets through the configure now.  It still fails due to the Mincionda problem; I pushed that change about 5 minutes too late for it to get into the nightly.

**Comment by hainm** [comment]
I will trigger another build to see.

**Comment by multiplemonomials** [comment]
No, no idea.  Can you try with `make -j1 VERBOSE=1`?

**Comment by hainm** [comment]
travis issue, compile fine now. thx,
