### ISSUE TITLE
Not compatible with Anaconda's CMake

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#67]
`cmake` from `conda-forge` adds Anaconda's library directories to its search path, which causes Anaconda's broken libraries to get used instead of the system ones.  I need to see if there is any sort of fix/workaround.

**Comment by multiplemonomials** [comment]
OK, I spent most of today working on this, and I think I've finally cracked it.

**Comment by multiplemonomials** [comment]
The first problem was that I didn't rally understand what Anaconda was previously.  I thought it was just a python interpreter with a penchant for bundling lots of libraries, but in reality, it's really more of a distro-within-a-distro for scientific computing with Python.

**Comment by multiplemonomials** [comment]
In that vein, we actually do want to use libraries from Anaconda, as long as they work.

**Comment by multiplemonomials** [comment]
The first issue was with `undefined reference to tputs` with internal readline (#56).  This turned out to be because there are some versions of `libncurses` that include `termcap` functions, and some that don't.  I had only encountered versions that did, but Anaconda's doesn't.  

cmake-buildscripts commit 142b49bd53f8 and amber commit d7b76ab8 fix this issue.

**Comment by multiplemonomials** [comment]
I also reverted commit 9e046b8e3, since we actually do want to find Anaconda libraries.

**Comment by hainm** [comment]
awesome new. 

> It's really more of a distro-within-a-distro for scientific computing with Python.

yes, that's correct. Due to the popularity of conda (Anaconda/miniconda) for building and distributing package, it is extended to anything; like I mentioned before, I just "conda install cmake -c conda-forge" without bothering about "sudo"; the distribution is consistent, user does not need when to use yum, apt-get, brew install or ... :D 

So we (amber) are trying hard to let user use Miniconda (a subset of Anaconda).

**Comment by multiplemonomials** [comment]
The second issue was with a mismatch in the version of `libgfortran` bundled with Anaconda, and the version used by the compiler (#62).  The problem was happening because FindMKL.cmake was, well, finding MKL inside Anaconda, and using that for Amber.  This caused CMake to pass the `-Lminiconda3/lib` flag to the linker, so it was picking up an unwanted `libgfortran` along the way.  

You are supposed to be able to disable this behavior with `cmake_policy CMP0003`, but that totally didn't work for me.  So, I rewrote FindMKL to use imported targets, and now CMake passes the libraries by full path and doesn't use the bad flag. 

Commit d1d3b872 fixes this issue.

**Comment by multiplemonomials** [comment]
The third issue is with CMake complaning about `unable to generate a safe search path ... /usr/lib/libz.so is shadowed by miniconda3/lib/libz.so`.  This isn't really fixable because there really isn't a way to have a safe RPATH with the same library in both locations.  The best solution is to just put the `anaconda3/lib` folder on the search path ahead of the system libraries, so CMake will find those first.  With my earlier changes, CMake will now ignore Anaconda's bad `libncurses.so` and keep searching until it finds a working one.

**Comment by multiplemonomials** [comment]
The next thing I need to do is write code in the build scripts that detects an Anaconda installation and puts it first on the search path.  It should also do this with internal Miniconda, so we can use its MKL libraries.

Quick question @hainm : In `AmberTools/src/configure_python`, it says:
```
echo "Updating and installing required and optional packages..."
# don't need to install mkl (100 MB)
```
Is this still relevant, if we can now use the MKL libraries from Miniconda?  Should I have `USE_MINICONDA` always download and use MKL, or should I make an option to control it?

Anyway I'm going to take a break for a while.  That was exhausting.

**Comment by hainm** [comment]
> # don't need to install mkl (100 MB)

yeah, this is intention. One of the core developers complained about big miniconda size so we were trying to download less as much as possible.

> or should I make an option to control it?

a good idea.

**Comment by multiplemonomials** [comment]
This should be fixed now!  Anaconda will be detected and used automatically.
