### ISSUE TITLE
python package checking should print out missing packages

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#7]
currently the code check if having numpy, if not exit -> user install numpy -> rerun cmake -> stuck with scipy -> install -> rerun -> stuck with matplotlib.  I think you should check all of them first.

**Comment by multiplemonomials** [comment]
Alright, error now looks like this:
```
Checking for Python package numpy -- not found
Checking for Python package scipy -- not found
Checking for Python package matplotlib -- not found
Checking for Python package cython -- not found
CMake Error at cmake/PythonConfig.cmake:81 (message):
  Missing required Python packages: numpy scipy matplotlib cython.  Please
  install these and try again, or set USE_MINICONDA to TRUE to create a
  python environment automatically.
```

**Comment by hainm** [comment]
Sounds good to me.

Hai

**Comment by multiplemonomials** [comment]
Also, in the next version, you won't be able to fool the python package check by changing `PYTHON_EXECUTABLE` to something else after the checks passed.

**Comment by multiplemonomials** [comment]
This is now merged into `master`.
