### ISSUE TITLE
get_lib_type(): library /usr/local/lib/libbz2.dylib does not exist!

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#72]
hi

```
export PATH=/usr/local/gfortran/bin:$PATH

which gcc g++

cmake \
    -DFORCE_INTERNAL_LIBS=readline \
    -DCMAKE_INSTALL_PREFIX=$HOME/amber_git/install_gnu \
    -DBUILD_GUI=FALSE \
    -DUSE_MINICONDA=FALSE \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DPYTHON_EXECUTALE=`which python` \
    ../amber

make install -j 4
```

**Comment by hainm** [comment]
do you setup on jenkins with different command combinations yet? I feel like getting new errors everyday. :D

**Comment by hainm** [comment]
should ad some regression tests to prevent that.

**Comment by multiplemonomials** [comment]
Can you please provide the logs using the script on the wiki?  I need a bit more info to troubleshoot this.  

Also, does that library actually exist?  Do you know if you changed anything that might've caused this?

Thanks

**Comment by hainm** [comment]
no, that lib does not exists. The thing is 'cmake amber' won't raises anything.

will add log later. ( a bit lazy to report so many reports ).

**Comment by hainm** [comment]
> Do you know if you changed anything that might've caused this?

No I don't. (I was just trying to reproduce the travis pysander error).

**Comment by hainm** [comment]
here we go.

[errorreport.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1384423/errorreport.txt)

**Comment by multiplemonomials** [comment]
The pysander error should be a pretty easy fix.  All that has to be done is add `-Wl,-rpath @loader_path/../../..` to its linker flags when it's being built by CMake.

**Comment by hainm** [comment]
I can not reproduce the the pysander issue on my mac (use with "cmake ../amber [and some commands]), so I was try to use exact command used on travis, but get stuck with posted issue here.

**Comment by multiplemonomials** [comment]
Whoops, I just realized that the script on the wiki doesn't include the one file I actually need to solve this issue.  I fixed the wiki now.  Do you mind also sending CMakeCache.txt?

**Comment by hainm** [comment]
[CMakeCache.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1384632/CMakeCache.txt)

**Comment by multiplemonomials** [comment]
OK, I honestly have no idea about what could have caused this, except if those libraries used to exist but were since deleted.  Can you try deleting your build directory and configuring from scratch?

**Comment by hainm** [comment]
I think I always do that from scratch when reporting to you. Will try again tonight.

**Comment by multiplemonomials** [comment]
This is honestly one of the strangest errors I've ever seen, and I can't imagine how it came up with paths to libraries that don't exist.  Please make sure that both `CMakeCache.txt` and `CMakeFiles` have been completely eradicated before you try again; I don't know what else it could be.

**Comment by hainm** [comment]
I've tried again (5 times with completely empty folder, lol), no luck. Let me do some digging.

**Comment by multiplemonomials** [comment]
Thanks!

**Comment by hainm** [comment]
so if I only use this command

```
cmake \
    ../../amber
```

the process complete nicely (with miniconda installed).

However, the below will give missing library error like I mentioned. I am eliminating one option at a time to see what caused the issue.

```
cmake \
    -DCMAKE_INSTALL_PREFIX=$HOME/amber_git/install-issue-72 \
    -DPYTHON_EXECUTABLE=$HOME/miniconda3/bin/python \
    -DUSE_MINICONDA=FALSE \
    -DFORCE_INTERNAL_LIBS=readline \
    ../../amber
```

**Comment by hainm** [comment]
believe me or not, omitting the line
`-DCMAKE_INSTALL_PREFIX=$HOME/amber_git/install-issue-72` would resolve the issue. I wanna cry.

**Comment by multiplemonomials** [comment]
Actually `CMAKE_INSTALL_PREFIX` is included in certain search paths in CMake.  And setting it changes it from the default value of <drumroll> `/usr/local`.

I think we're on to something here!

**Comment by multiplemonomials** [comment]
Hey, I just had a thought about this issue!  You know `pkg-config` files, right?  CMake provides a similar mechanism, and I wonder if it's getting these paths from one of those that was left on your system sonewhere.

Can you run the following command (I hope I got the syntax right)
```sh
find / \( -name '*.cmake' -or -name '*.txt' \) -exec grep -Iin 'readline' {}
```

That should find any CMake package-config file left anywhere that reference `readline`

**Comment by hainm** [comment]
it returns too many lines (still running, already got 800 lines).

I think this is the issue:

The log saying 
```
CMake Error at cmake/LibraryTracking.cmake:35 (message):
  get_lib_type(): library /usr/local/lib/libbz2.dylib does not exist!
```

but 

```
$ ls /usr/local/lib/libbz2.dylib 
/usr/local/lib/libbz2.dylib
```

**Comment by hainm** [comment]
due to symlink?

```
$ ll /usr/local/lib/libbz2.dylib 
lrwxr-xr-x  1 haichit  admin  16 Oct 13 23:40 /usr/local/lib/libbz2.dylib@ -> libbz2.1.0.dylib
```

**Comment by hainm** [comment]
oh boy, does cmake accidentally made the symlink in my /usr/local folder?

```
$ ll /usr/local/lib/libreadline.dylib 
lrwxr-xr-x  1 haichit  admin  15 Oct 13 23:40 /usr/local/lib/libreadline.dylib@ -> libedit.3.dylib

$ cat /usr/local/lib/libreadline.dylib 
cat: /usr/local/lib/libreadline.dylib: No such file or directory
```

**Comment by hainm** [comment]
uhm, remove those empty files won't help, still getting "get_lib_type(): library /usr/local/lib/libbz2.dylib does not exist!"

**Comment by multiplemonomials** [comment]
wait, what?

You said in an earlier post, 

> no, that lib does not exists

**Comment by multiplemonomials** [comment]
>remove those empty files won't help, still getting "get_lib_type(): library /usr/local/lib/libbz2.dylib does not exist!"

You tried deleting and recreating the build folder, right?

**Comment by hainm** [comment]
> wait, what?

> You said in an earlier post,

>> no, that lib does not exists

Yes, I think at that moment, the file did not exist. After few days with trying a bunch of stuff, that file appeared but it's empty and is a symlink to a non-existing file.


> You tried deleting and recreating the build folder, right?

oh, good point. I forgot to delete the existing build folder. Deleting it and tried again with the command in my 1st post, work now. wanna cry.

**Comment by hainm** [comment]
I think we can close this now.

**Comment by multiplemonomials** [comment]
> wanna cry.

Don't wory, me too at times :P
