### ISSUE TITLE
print cmake command in the log?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#75]
hi,

saying I am using

```
cmake ../amber -Dblabla ...
```

can it be printed out in the log?

**Comment by multiplemonomials** [comment]
Actually, any variables that you define on the command line are saved in `CMakeCache.txt`.  So I already have that information by looking at the standard bug report data.

**Comment by hainm** [comment]
how's about cmake path?

I only see below in log:
```
-- CMake Version: 3.9.4
```
