### ISSUE TITLE
any way to prevent typos?

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#76]
e.g:

I've been tracking down some errors and realize that I made a typos

```
-DPYTHON_EXECUTALE=$HOME/miniconda3/bin/python
```

**Comment by multiplemonomials** [comment]
CMake will give you a warning, like
```
Warning: manually specified variable PYTHON_EXECUTALE was not used by this project
```
at the end of the configuration process, if you made a mistake like this.

This should be what you're looking for.
