### ISSUE TITLE
cmake path

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#77]
hi,

assuming I have different cmake in path_A and path_B.
The path_A is in PATH but its cmake is buggy and I want to use non-buggy cmake in path_B.
path_B is not in PATH

- step 1: ok
```
/path/to/cmake/in/path_B ../amber
```

- step 2: error with "cmake: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory"
```
make install
```

The non-working cmake in path_A gives the same error. So I guess that in "step 2", the cmake in PATH is picked up.

So I guess specify absolute path to working cmake in step 1 is not sufficient for step 2, right?

**Comment by hainm** [comment]
do feel free to change the issue title.

**Comment by multiplemonomials** [comment]
> So I guess specify absolute path to working cmake in step 1 is not sufficient for step 2, right?

It's certainly supposed to be!  Can you take a full bug report as specified on the wiki?

**Comment by hainm** [comment]
ok, hold on.

**Comment by hainm** [comment]
please check here.

[issue-77.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1385189/issue-77.txt)

**Comment by multiplemonomials** [comment]
Should be fixed by Amber master commit 3692a54d63.
