### ISSUE TITLE
nab.cmake for external use

### ISSUE THREAD

**Issue by multiplemonomials** [Amber-MD/cmake-buildscripts#81]
Dr. Case has agreed that this would be a good feature.  It would require setting up a whole target exporting system though.

**Comment by dacase** [comment]
Can I change my mind?  Since last October, I've worked more on moving nab functionality to C.  We still need nab inside AmberTools, but I'm less eager to spend/waste time on a standalone version.

**Comment by multiplemonomials** [comment]
Yeah, me too, to be honest.
