### ISSUE TITLE
File 'netcdf_nc_data.mod' opened at (1) is not a GNU Fortran module file

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#82]
hi, netcdf again.

I've been making the docker image centos 5 with cmake 3.9; you can try via

```
docker pull ambermd/amber-build-box-cmake
```

Please see error report below
[cmakeoutput.log](https://github.com/Amber-MD/cmake-buildscripts/files/1405468/cmakeoutput.log)

[errorreport.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1405466/errorreport.txt)

**Comment by multiplemonomials** [comment]
Uh, you didn't attach a `makeoutput.log` file.  Do you mind attaching that as described on the wiki?  Thanks.

**Comment by hainm** [comment]
here we go.

[makeoutput.txt](https://github.com/Amber-MD/cmake-buildscripts/files/1420771/makeoutput.txt)

**Comment by hainm** [comment]
I am able to compile amber in centos 5 docker now (from my 1st post).

Just for the record
```
cmake \
    -DCMAKE_INSTALL_PREFIX=/work/cmake-reports/install-from-docker \
    -DPYTHON_EXECUTABLE=`which python` \
    -DUSE_MINICONDA=FALSE \
    ../../amber

make install
```

Nice job, thanks.
