### ISSUE TITLE
Need option to disable Python package checks.

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#83]
hey man,

since python is not that great in this aspect, we need to build multiple python binary versions.
Does cmake support this yet?

This is how I would do with non-cmake

```
./configure --skip-python gnu
make install # build all non-python stuff
./configure --with-python=python2.7 gnu
cd AmberTools/src && make python_serial
./configure --with-python=python3.6 gnu
cd AmberTools/src && make python_serial
```

so there will be `$AMBERHOME/lib/pythonX.Y/` folders (X.Y=2.7 and 3.6)

**Comment by multiplemonomials** [comment]
You can do it though the same process as the old configure script: something like this
```sh
cmake ../amber -DPYTHON_EXECUTABLE=/usr/bin/python2.7
make install
cmake ../amber -DPYTHON_EXECUTABLE=/usr/bin/python3.6
```

Do you want me to make it do this automatically?  As in, you could run `make` once, and it would build both versions. If so, how should that work? What would be the interface?

**Comment by hainm** [comment]
great, will try tonight. thanks.

> Do you want me to make it do this automatically? As in, you could run make once, and it would build both versions. If so, how should that work? What would be the interface?

No we should not. Should keep the interface minimal to avoid maintenance burden.

**Comment by hainm** [comment]
quick questions
- how can I skip checking checking scipy, matplotlib, ...? Those are required at run time, not install time.
- how can I force cmake to build all internal libs? (e.g: fftw, lapack, ...), assume that I don't know all of them to specify in command. (just very minor point).

**Comment by hainm** [comment]
uhm, currently I need to edit `cmake_install.cmake` to update `set(CMAKE_INSTALL_PREFIX "/Users/haichit/amber_git/cmake/tmp")` for every python build.

other than that, things are working. thanks.

**Comment by multiplemonomials** [comment]
> how can I skip checking checking scipy, matplotlib,
There isn't currently an easy way to do that.  Do you want me to put that in?

>  Those are required at run time, not install time.
I just added the Python check because the configure script had/has it.  Should I take it out?

**Comment by multiplemonomials** [comment]
> assume that I don't know all of them to specify in command. (just very minor point).

From `amber/CMakeLists.txt`, the authoritative list:

```
 set(BUNDLED_3RDPARTY_TOOLS blas lapack arpack byacc ucpp c9x-complex netcdf netcdf-fortran pnetcdf fftw readline xblas mpi4py perlmol)
```

**Comment by hainm** [comment]
thanks.

**Comment by hainm** [comment]
> There isn't currently an easy way to do that. Do you want me to put that in?

Yes, please.

> I just added the Python check because the configure script had/has it. Should I take it out?

It is good to have the checking.

**Comment by multiplemonomials** [comment]
Just curious, why do you need this option?

**Comment by hainm** [comment]
which one?

**Comment by multiplemonomials** [comment]
the one to disable Python package checking

**Comment by hainm** [comment]
In this case, I only need python itself to compile the binary.
I need to build python 2.7, 3.4, 3.5, 3.6 and do not want to install a bunch of python packages.
Which makes sense since I don't need to the build and pack the binary.

**Comment by multiplemonomials** [comment]
Oh, OK, I see.  I can put that reason in the documentation then

**Comment by hainm** [comment]
thanks

>

**Comment by multiplemonomials** [comment]
You should now just be able to set `SKIP_PYTHON_PACKAGECHECKS` to `TRUE` to disable the checks.

**Comment by hainm** [comment]
Why using plural in CHECKS?

**Comment by multiplemonomials** [comment]
Wait, sorry, the variable name is actually `SKIP_PYTHON_PACKAGE_CHECKS`

I used a plural because there are multiple checks that it is skipping.

**Comment by hainm** [comment]
I think it's just flag to turn thing on/off so should not be plural.
(Just opinion from non-native speaker :d).
