### ISSUE TITLE
Adding -DCMAKE_INSTALL_PREFIX will rebuild

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#84]
so in this issue #83, I am able to build multiple versions. In final step, I add 
`-DCMAKE_INSTALL_PREFIX=/pat/to/something` and `make install`. It seems to me that the whole build process is repeated.

can you confirm this? thanks.

**Comment by hainm** [comment]
uhm, I knew why I do not add prefix from the beginning: https://github.com/Amber-MD/cmake-buildscripts/issues/72#issuecomment-336676598

**Comment by multiplemonomials** [comment]
No, only a small fraction of the build gets repeated.  There are a few programs (nab and reduce) that have absolute paths compiled into them, and these have to be rebuilt when the install prefix changes.  And when `nab2c` is rebuilt, that triggers a rebuild of all NAB programs.  

That's still only about 5% of the total Amber code, though.  It does not do a full rebuild.

**Comment by hainm** [comment]
those are extra

- rism/
- libpbsa
- gbnr6
- sander and sander.LES

**Comment by multiplemonomials** [comment]
Huh, that doesn't happen on my machines, but it might be because it can have to re-link things to change RPATHS.

Check [the Jenkins build log](http://www.jasonswails.com:8888/job/Amber/job/AmberCI/88/consoleFull), where it rebuilds a second time to change installation directories.

**Comment by hainm** [comment]
yeah, this is just minor issue.
