### ISSUE TITLE
libnab.a (non-cmake) vs libnab.dylib (cmake)

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#87]
hi, why there is difference here?

**Comment by multiplemonomials** [comment]
CMake builds it as a shared library, whereas the Makefile build system builds it as static.  I think that library got converted to shared as part of my initiative to make all Amber libraries shared where it was possible.  

It should work the same as the static version though, other than the RPATH issues on macs.  Is there any specific problem you're having with it?  

Also, note that you could use the `STATIC` option to build all Amber libraries including `libnab` as static, if you wanted.

**Comment by multiplemonomials** [comment]
Did I answer your question?

**Comment by hainm** [comment]
> Is there any specific problem you're having with it?

No I don't. 

> Did I answer your question?

yes, thanks.
