### ISSUE TITLE
cmake -DPRINT_PACKAGING_REPORT=TRUE <path to source dir> >cmakeoutput.log 2>&1

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#88]
can you confirm (try) that command work? I can not save any output to `cmakeoutput.log`

Basically I ran
`
$ cmake ~/amber_git/amber     -DUSE_MINICONDA=False     -DPYTHON_EXECUTABLE=/Users/haichit/miniconda3/bin/python     -CMAKE_INSTALL_PREFIX=/Users/haichit/amber_git/cmake/stable  >cmakeoutput.log 2>&1
`

```
$ ls cmakeoutput.log
ls: cmakeoutput.log: No such file or directory
```

**Comment by hainm** [comment]
This does not work either
```
cmake -DPRINT_PACKAGING_REPORT=TRUE \
    -DPRINT_PACKAGING_REPORT=TRUE \
    -DUSE_MINICONDA=False \
    -DPYTHON_EXECUTABLE=/Users/haichit/miniconda3/bin/python \
    -CMAKE_INSTALL_PREFIX=/Users/haichit/amber_git/cmake/stable \
    ~/amber_git/amber >cmakeoutput.log 2>&1
```

**Comment by multiplemonomials** [comment]
It works fine for me.  What if you ditch the `2>&1`?

**Comment by hainm** [comment]
does not work either. I think my mac is crazy. Will do google search then. thanks.

**Comment by hainm** [comment]
@multiplemonomials so I put all commands in a run.sh script. 

The `sh run.sh` does not write to cmakeoutput.log but the `source run.sh` does.

**Comment by multiplemonomials** [comment]
Huh, strange.  Glad you fixed it though.

**Comment by hainm** [comment]
damn, it's super weird with cmake output

```
cmake -DPRINT_PACKAGING_REPORT=TRUE \
    -DPYTHON_EXECUTABLE=$HOME/miniconda3/envs/py2/bin/python \
    -DUSE_MINICONDA=False \
    -DCMAKE_INSTALL_PREFIX=/Users/haichit/amber_git/cmake-reports/multi-pythons \
    $HOME/amber_git/amber >& cmakeoutput.log # I can not see the cmakeoutput.log

make install >& makeoutput.log # I could see the makeoutput.log here
```
