### ISSUE TITLE
cmake -DUSE_MINICONDA=True

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#94]
`-- Found system Anaconda at /Users/haichit/miniconda3.  It will be used as a Python interpereter, and for additional shared libraries
-- It is not possible to avoid using Anaconda if it is on the PATH.  To build Amber without using Anaconda, remove it from your PATH.
-- Found PythonInterp: /Users/haichit/miniconda3/bin/python (found version "3.6.1") 
`

Should you mention something that downloading miniconda will be ignored? or just stop the process?

**Comment by multiplemonomials** [comment]
OK, I added this warning in this situation:
```
-- It is not possible to avoid using Anaconda if it is on the PATH.  To build Amber without using Anaconda, remove it from your PATH.
-- To use a different Anaconda install, just move it to the front of your PATH and rerun CMake.
-- To change the Python interpreter in use to a different one inside Anaconda, set the PYTHON_EXECUTABLE variable to point to it.
CMake Warning at cmake/PythonInterpreterConfig.cmake:25 (message):
  DOWNLOAD_MINICONDA is TRUE, but this will be ignored because Anaconda was
  found on your path.
Call Stack (most recent call first):
  CMakeLists.txt:123 (include)
```

**Comment by hainm** [comment]
> It is not possible to avoid using Anaconda if it is on the PATH.

why is it?

**Comment by multiplemonomials** [comment]
CMake will find Anaconda's libraries as long as they are anywhere on the path.  Technically it might be possible to use a different Python interpreter, but you'll always end up linking to libraries from Anaconda if it's on your PATH.  As I understand it, that's rarely a bad thing, right?

**Comment by hainm** [comment]
yeah, I am ok with that. But just be aware that many developers do not care much about python or Anaconda so they might have different opinions. 

In general, if user specify something, we should not ignore it and do our own way. If we don't like their way, it would be better to raise error (my personal opinion).

**Comment by hainm** [comment]
cc @swails here since he has more experience about those.

**Comment by multiplemonomials** [comment]
I suppose if we need to, I can make it so CMake removes Anaconda from its PATH automatically, if this turns out to be something people want.
