### ISSUE TITLE
add pytest to python checking + miniconda install

### ISSUE THREAD

**Issue by hainm** [Amber-MD/cmake-buildscripts#96]
hi,

currently pytraj is using pytest to run its tests in ambertools, may be we can add checking (and install if installing miniconda). It's light and pure python.

```
AmberTools/src (master) $ cat python_requirement.txt 
numpy
matplotlib
scipy
ipython
notebook
cython
pytest
```

**Comment by hainm** [comment]
can cmake use `python_requirement.txt ` file to check?

**Comment by multiplemonomials** [comment]
Wait but isn't Cython only required for developer builds?  Or did that change?

**Comment by hainm** [comment]
yeah, I add a subset of pytraj test to AmberTools recently (May).

**Comment by multiplemonomials** [comment]
So... cython is now a requirement even for release builds?

**Comment by hainm** [comment]
On Sun, Nov 19, 2017 at 1:31 PM Jamie Smith <notifications@github.com>
wrote:

> So... cython is now a requirement even for release builds?
>

No, only for dev build.

Uhm, hold on this issue about pytest, I am not sure if we should require
user to have it.

**Comment by multiplemonomials** [comment]
Did you ever make a decision about this?

**Comment by hainm** [comment]
Not yet, but just ‘no need’ for now. Thanks

**Comment by multiplemonomials** [comment]
OK, I'm closing this for now; please reopen it if/when you want me to add the feature.
