### ISSUE TITLE
NetCDF Fortran interface fails to build

### ISSUE THREAD

**Issue by tluchko** [Amber-MD/cmake-buildscripts#99]
Building Amber always dies with the same error

```
/home1/02211/tluchko/work/amber-cmake.git/AmberTools/src/netcdf-fortran-4.4.4/fortran/module_netcdf_fortv2_c_interfaces.f90(609): error #6683: A kind type parameter must be a compile-time constant.   [C_PTRDIFF_T]
 Integer(C_PTRDIFF_T), Intent(INOUT) :: cmap(:)
---------^
compilation aborted for /home1/02211/tluchko/work/amber-cmake.git/AmberTools/src/netcdf-fortran-4.4.4/fortran/module_netcdf_fortv2_c_interfaces.f90 (code 1)
```
I've had this error on my CentOS 6.6 machine with both GNU 4.4 and Intel 17.0.4, on Stampede2, CentOS 7.4 with Intel 17.0.4, and OS X 10.12.6 with GNU 4.4 (MacPorts).  However, I did successfully install on Stampede2, CentOS 7.4 with GNU 7.1 and on OS X 10.12.6 with GNU 6.4 (MacPorts).

I suspect that the wrong compiler is somehow being picked up. From this thread it looks like NetCDF doesn't compile with older versions of gcc, producing this error. They say that gcc >= 4.8 should work. But this doesn't explain why the Intel compilers don't work.

[errorreport.tar.gz](https://github.com/Amber-MD/cmake-buildscripts/files/1621637/errorreport.tar.gz)

**Comment by tluchko** [comment]
I'm only including the Intel files since the failure with GNU 4.4 seems to be expected and 4.8 is now the minimum version supported.
[netcdf-build-files.tar.gz](https://github.com/Amber-MD/cmake-buildscripts/files/1624083/netcdf-build-files.tar.gz)

**Comment by multiplemonomials** [comment]
Oh wow, I really screwed that fix up.  Turns out I had:
```cmake
IF (COMPILE_SUCCESS)
  set(HAVE_TS29113_SUPPORT TRUE)
  message(STATUS "netcdf-fortran: Detected TS29113 support in Fortran compiler")
ELSE ()

  set(HAVE_TS29113_SUPPORT TRUE)
  ...
```

so it was set to true regardless of the result of the test.

**Comment by multiplemonomials** [comment]
Can you try again with Amber master commit `739d56300`?

**Comment by tluchko** [comment]
NetCDF seems to be fixed. It is now failing on pubfft.F90. There are a lot of warnings and this error

```
/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/rism/pubfft.F90(305): error #6633: The type of the actual argument differs from the type of the dummy argument.   [WSAVE]
   call cffti1 (n,wsave(iw1),wsave(iw2))
-----------------------------^
c
```

[errorreport.tar.gz](https://github.com/Amber-MD/cmake-buildscripts/files/1624433/errorreport.tar.gz)

**Comment by multiplemonomials** [comment]
I haven't fixed this issue yet.  CMake seems to automatically enable Intel Fortran's extra error-checking facilities, which is good, but they actually uncover a lot of errors, which is bad.  I already spend over an hour fixing nitty-gritty Fortran type errors in Arpack...

**Comment by multiplemonomials** [comment]
The code causing the error is 
```fortran
   integer      n
   _REAL_       wsave(*)

   integer      iw1
   integer      iw2

   <snip>

   call cffti1 (n,wsave(iw1),wsave(iw2))
```

where `cffti1` is declared as

```
subroutine cffti1 (n,wa,ifac)
   implicit none
   integer:: i, i1, ib, ido, idot, ifac, ii, ip, ipm, j, k1, l1, l2, &
        ld, n, nf, nl, nq, nr, ntry, ntryh
   _REAL_ :: arg, argh, argld, fi, tpi, wa
   dimension       wa(*)      ,ifac(*)    ,ntryh(4)
```

I don't know enough Fortran to be able to fix this code while preserving its original behavior, so I emailed @dacase about it.

**Comment by tluchko** [comment]
It looks like this problem has been fixed in `$AMBERHOME/AmberTools/src/sander/pubfft.F90`. The RISM version is nearly identical except for the fixes and some changes I made for `rism1d`. I updated the RISM version and everything compiles and the tests pass, though the warnings are still there. I pushed this to master.

It now gets stuck at
```
[ 28%] Building Fortran object AmberTools/src/pbsa/CMakeFiles/libpbsa.dir/pb_p3m.F90.o
cd /home/tluchko/projects/testing/intel-cmake/AmberTools/src/pbsa && /opt/intel/compilers_and_libraries_2017.4.196/linux/bin/intel64/ifort  -DBINTRAJ -DFFTW -DLIBPBSA -DUSE_MKSTEMP -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -Dlibpbsa_EXPORTS -I/home/tluchko/projects/testing/intel-cmake/amber-modules/pbsa/lib -I/home/tluchko/projects/testing/intel-cmake/amber-modules/amberlib -I/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/fftw-3.3/api -I/home/tluchko/projects/testing/intel-cmake/AmberTools/src/fftw-3.3/api -I/opt/intel/mkl/include -I/home/tluchko/projects/testing/intel-cmake/AmberTools/src/netcdf-fortran-4.4.4/fortran/modules -I/home/tluchko/projects/testing/intel-cmake/AmberTools/src/netcdf-fortran-4.4.4 -I/home/tluchko/projects/testing/intel-cmake/AmberTools/src/netcdf-fortran-4.4.4/libsrc -I/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/netcdf-fortran-4.4.4 -I/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/netcdf-fortran-4.4.4/libsrc -I/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/netcdf-fortran-4.4.4/fortran -I/home/tluchko/projects/testing/intel-cmake/AmberTools/src/netcdf-fortran-4.4.4/fortran -I/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/netcdf-fortran-4.4.4/fortran/. -I/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/netcdf-4.3.0/liblib/../include -I/home/tluchko/projects/testing/intel-cmake/AmberTools/src/netcdf-4.3.0/liblib  -warn all -warn nounused -module ../../../amber-modules/pbsa/lib -fPIC   -O0 -c /home/tluchko/projects/code/amber-cmake.git/AmberTools/src/pbsa/pb_p3m.F90 -o CMakeFiles/libpbsa.dir/pb_p3m.F90.o
/home/tluchko/projects/code/amber-cmake.git/AmberTools/src/pbsa/pb_p3m.F90(584): error #8000:  There is a conflict between local interface block and external interface block.   [DIST]
   function density_deriv_atom (dist,dist0,dx)
--------------------------------^
compilation aborted for /home/tluchko/projects/code/amber-cmake.git/AmberTools/src/pbsa/pb_p3m.F90 (code 1)
make[3]: *** [AmberTools/src/pbsa/CMakeFiles/libpbsa.dir/pb_p3m.F90.o] Error 1
make[3]: Leaving directory `/home/tluchko/projects/testing/intel-cmake'
make[2]: *** [AmberTools/src/pbsa/CMakeFiles/libpbsa.dir/pb_p3m.F90.o.provides] Error 2
make[2]: Leaving directory `/home/tluchko/projects/testing/intel-cmake'
make[1]: *** [AmberTools/src/pbsa/CMakeFiles/libpbsa.dir/all] Error 2
make[1]: Leaving directory `/home/tluchko/projects/testing/intel-cmake'
make: *** [all] Error 2
```

**Comment by multiplemonomials** [comment]
I did figure out how to turn off the interface checking, but the question is, should I?  I feel like it would be better to actually fix the issues, it's just that I don't have the requisite Fortran skills to comfortably address these problems without breaking anything.

**Comment by tluchko** [comment]
I agree that the issues should be fixed.  However, this will need to be done by the individual developers and will take time. I don't know how many issues there are.

Currently the code does pass our test suite. And if the CMake build doesn't work the code will still be built with the same issues using the old build system or using a different compiler.

I suggest a flag that can turn on interface checking to help us catch potentially bad code since it will be some time before we can expect the whole code to compile with all checks turned on.  Also a flag that turns on debug flags and works with Valgrind would be nice but that's a different topic.

**Comment by multiplemonomials** [comment]
Good point, I was thinking the same thing.

I added this option in commit caec44b74f as `IFORT_CHECK_INTERFACES`, and it defaults to false, so it will not produce errors unless a developer explicitly tells it to with `-DIFORT_CHECK_INTERFACES=TRUE`.  Give it another try, it should work.

Also, what do you mean about debug flags?  The build system already has that capability, adding the options 
```cmake
-DOPTIMIZE=FALSE -DCMAKE_BUILD_TYPE=Debug
```
will turn off optimizations and enable debugging information.  Is that not good for Valgrind for some reason?

**Comment by swails** [comment]
How do you keep optimizations on but include debug symbols? That’s been very useful to me on many occasions hunting down heisenbugs.

**Comment by multiplemonomials** [comment]
```
-DOPTIMIZE=TRUE -DCMAKE_BUILD_TYPE=Debug
```

`OPTIMIZE=TRUE` is the default, so you can also just pass the `CMAKE_BUILD_TYPE` flag.

**Comment by tluchko** [comment]
@multiplemonomials, the debug and optimize flags should be sufficient.  It seems I didn't read the documentation carefully enough.

The build now works with Intel.  Thanks. I'm looking forward to digging into all of the features.
